//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:12:18 PM MSK 
//


package ru.crystals.pos.egais.documents;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Позиция
 * 
 * <p>Java class for ActChargeOnPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActChargeOnPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType"/>
 *         &lt;element name="Product" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}ProductInfo_v2"/>
 *         &lt;element name="Quantity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="InformF1F2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InformF1F2Reg" type="{http://fsrar.ru/WEGAIS/ActChargeOn_v2}InformF1F2RegType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarkCodeInfo" type="{http://fsrar.ru/WEGAIS/CommonEnum}MarkCodeInfoType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActChargeOnPositionType", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", propOrder = {

})
public class ActChargeOnPositionType2 {

    @XmlElement(name = "Identity", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", required = true)
    protected String identity;
    @XmlElement(name = "Product", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", required = true)
    protected ProductInfoV2 product;
    @XmlElement(name = "Quantity", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "InformF1F2", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", required = true)
    protected ActChargeOnPositionType2 .InformF1F2 informF1F2;
    @XmlElement(name = "MarkCodeInfo", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2")
    protected MarkCodeInfoType markCodeInfo;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInfoV2 }
     *     
     */
    public ProductInfoV2 getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInfoV2 }
     *     
     */
    public void setProduct(ProductInfoV2 value) {
        this.product = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the informF1F2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActChargeOnPositionType2 .InformF1F2 }
     *     
     */
    public ActChargeOnPositionType2 .InformF1F2 getInformF1F2() {
        return informF1F2;
    }

    /**
     * Sets the value of the informF1F2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActChargeOnPositionType2 .InformF1F2 }
     *     
     */
    public void setInformF1F2(ActChargeOnPositionType2 .InformF1F2 value) {
        this.informF1F2 = value;
    }

    /**
     * Gets the value of the markCodeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MarkCodeInfoType }
     *     
     */
    public MarkCodeInfoType getMarkCodeInfo() {
        return markCodeInfo;
    }

    /**
     * Sets the value of the markCodeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkCodeInfoType }
     *     
     */
    public void setMarkCodeInfo(MarkCodeInfoType value) {
        this.markCodeInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InformF1F2Reg" type="{http://fsrar.ru/WEGAIS/ActChargeOn_v2}InformF1F2RegType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "informF1F2Reg"
    })
    public static class InformF1F2 {

        @XmlElement(name = "InformF1F2Reg", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", required = true)
        protected InformF1F2RegType informF1F2Reg;

        /**
         * Gets the value of the informF1F2Reg property.
         * 
         * @return
         *     possible object is
         *     {@link InformF1F2RegType }
         *     
         */
        public InformF1F2RegType getInformF1F2Reg() {
            return informF1F2Reg;
        }

        /**
         * Sets the value of the informF1F2Reg property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformF1F2RegType }
         *     
         */
        public void setInformF1F2Reg(InformF1F2RegType value) {
            this.informF1F2Reg = value;
        }

    }

}
