//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:12:18 PM MSK 
//


package ru.crystals.pos.egais.documents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="WayBill" type="{http://fsrar.ru/WEGAIS/TTNSingle}WayBillType"/>
 *         &lt;element name="Ticket" type="{http://fsrar.ru/WEGAIS/Ticket}TicketType"/>
 *         &lt;element name="WayBillAct" type="{http://fsrar.ru/WEGAIS/ActTTNSingle}WayBillActType"/>
 *         &lt;element name="ConfirmTicket" type="{http://fsrar.ru/WEGAIS/ConfirmTicket}ConfirmTicketType"/>
 *         &lt;element name="TTNInformBReg" type="{http://fsrar.ru/WEGAIS/TTNInformBReg}WayBillInformBRegType"/>
 *         &lt;element name="ActInventory" type="{http://fsrar.ru/WEGAIS/ActInventorySingle}ActInventoryType"/>
 *         &lt;element name="ActChargeOn" type="{http://fsrar.ru/WEGAIS/ActChargeOn}ActChargeOnType"/>
 *         &lt;element name="ActInventoryInformBReg" type="{http://fsrar.ru/WEGAIS/ActInventoryInformBReg}ActInventoryInformBReg"/>
 *         &lt;element name="QueryAP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QuerySSP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QuerySP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryClients" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryClientVersion" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryRests" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryFormBHistory" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryResendDoc" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryFormA" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB"/>
 *         &lt;element name="QueryFormB" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB"/>
 *         &lt;element name="ActWriteOff" type="{http://fsrar.ru/WEGAIS/ActWriteOff}ActWriteOffType"/>
 *         &lt;element name="RepProducedProduct" type="{http://fsrar.ru/WEGAIS/RepProducedProduct}RepProducedType"/>
 *         &lt;element name="RepImportedProduct" type="{http://fsrar.ru/WEGAIS/RepImportedProduct}RepImportedType"/>
 *         &lt;element name="ReplySSP" type="{http://fsrar.ru/WEGAIS/ReplySSP}ReplySSP" minOccurs="0"/>
 *         &lt;element name="ReplySpirit" type="{http://fsrar.ru/WEGAIS/ReplySpirit}ReplySpirit" minOccurs="0"/>
 *         &lt;element name="ReplyClient" type="{http://fsrar.ru/WEGAIS/ReplyClient}ReplyClient" minOccurs="0"/>
 *         &lt;element name="ReplyAP" type="{http://fsrar.ru/WEGAIS/ReplyAP}ReplyAP" minOccurs="0"/>
 *         &lt;element name="ReplyRests" type="{http://fsrar.ru/WEGAIS/ReplyRests}ReplyRests" minOccurs="0"/>
 *         &lt;element name="ReplyFormA" type="{http://fsrar.ru/WEGAIS/ReplyFormA}ReplyFormA" minOccurs="0"/>
 *         &lt;element name="ReplyFormB" type="{http://fsrar.ru/WEGAIS/ReplyFormB}ReplyFormB" minOccurs="0"/>
 *         &lt;element name="ReplyHistFormB" type="{http://fsrar.ru/WEGAIS/ReplyHistFormB}ReplyHistFormB" minOccurs="0"/>
 *         &lt;element name="ReplyClientVersion" type="{http://fsrar.ru/WEGAIS/ReplyClientVersion}ReplyClientVersion" minOccurs="0"/>
 *         &lt;element name="QueryRejectRepProduced" type="{http://fsrar.ru/WEGAIS/QueryRejectRepProduced}QueryRejectRepProduced" minOccurs="0"/>
 *         &lt;element name="QueryRejectRepImported" type="{http://fsrar.ru/WEGAIS/QueryRejectRepImported}QueryRejectRepImported" minOccurs="0"/>
 *         &lt;element name="ReplySSP_v2" type="{http://fsrar.ru/WEGAIS/ReplySSP_v2}ReplySSP_v2" minOccurs="0"/>
 *         &lt;element name="ReplySpirit_v2" type="{http://fsrar.ru/WEGAIS/ReplySpirit_v2}ReplySpirit_v2" minOccurs="0"/>
 *         &lt;element name="ReplyClient_v2" type="{http://fsrar.ru/WEGAIS/ReplyClient_v2}ReplyClient_v2" minOccurs="0"/>
 *         &lt;element name="ReplyAP_v2" type="{http://fsrar.ru/WEGAIS/ReplyAP_v2}ReplyAP_v2" minOccurs="0"/>
 *         &lt;element name="ReplyRests_v2" type="{http://fsrar.ru/WEGAIS/ReplyRests_v2}ReplyRests_v2" minOccurs="0"/>
 *         &lt;element name="ReplyForm1" type="{http://fsrar.ru/WEGAIS/ReplyForm1}ReplyForm1" minOccurs="0"/>
 *         &lt;element name="ReplyForm2" type="{http://fsrar.ru/WEGAIS/ReplyForm2}ReplyForm2" minOccurs="0"/>
 *         &lt;element name="ReplyHistForm2" type="{http://fsrar.ru/WEGAIS/ReplyHistForm2}ReplyHistForm2" minOccurs="0"/>
 *         &lt;element name="WayBill_v2" type="{http://fsrar.ru/WEGAIS/TTNSingle_v2}WayBillType_v2"/>
 *         &lt;element name="WayBillAct_v2" type="{http://fsrar.ru/WEGAIS/ActTTNSingle_v2}WayBillActType_v2"/>
 *         &lt;element name="ActChargeOn_v2" type="{http://fsrar.ru/WEGAIS/ActChargeOn_v2}ActChargeOnType_v2"/>
 *         &lt;element name="ActInventoryInformF2Reg" type="{http://fsrar.ru/WEGAIS/ActInventoryInformF2Reg}ActInventoryInformF2Reg"/>
 *         &lt;element name="TTNInformF2Reg" type="{http://fsrar.ru/WEGAIS/TTNInformF2Reg}WayBillInformF2RegType"/>
 *         &lt;element name="QueryAP_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QuerySSP_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QuerySP_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryClients_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryRests_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryFormF1" type="{http://fsrar.ru/WEGAIS/QueryFormF1F2}QueryFormF1F2"/>
 *         &lt;element name="QueryFormF2" type="{http://fsrar.ru/WEGAIS/QueryFormF1F2}QueryFormF1F2"/>
 *         &lt;element name="ActWriteOff_v2" type="{http://fsrar.ru/WEGAIS/ActWriteOff_v2}ActWriteOffType_v2"/>
 *         &lt;element name="TransferFromShop" type="{http://fsrar.ru/WEGAIS/TransferFromShop}TransferFromShopType"/>
 *         &lt;element name="TransferToShop" type="{http://fsrar.ru/WEGAIS/TransferToShop}TransferToShopType"/>
 *         &lt;element name="QueryForm2History" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="RepInformF1Reg" type="{http://fsrar.ru/WEGAIS/RepInformF1Reg}RepPIInformF1RegType"/>
 *         &lt;element name="ReplyNoAnswerTTN" type="{http://fsrar.ru/WEGAIS/ReplyNoAnswerTTN}NoAnswerTTN"/>
 *         &lt;element name="QueryNATTN" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="QueryRestsShop_v2" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters"/>
 *         &lt;element name="ReplyRestsShop_v2" type="{http://fsrar.ru/WEGAIS/ReplyRestsShop_v2}ReplyRestsShop_v2" minOccurs="0"/>
 *         &lt;element name="Asiiu" type="{http://fsrar.ru/WEGAIS/Asiiu}Asiiu" minOccurs="0"/>
 *         &lt;element name="AsiiuTime" type="{http://fsrar.ru/WEGAIS/AsiiuTime}AsiiuTime" minOccurs="0"/>
 *         &lt;element name="ActChargeOnShop_v2" type="{http://fsrar.ru/WEGAIS/ActChargeOnShop_v2}ActChargeOnShopType_v2"/>
 *         &lt;element name="ActWriteOffShop_v2" type="{http://fsrar.ru/WEGAIS/ActWriteOffShop_v2}ActWriteOffShopType_v2"/>
 *         &lt;element name="InfoVersionTTN" type="{http://fsrar.ru/WEGAIS/InfoVersionTTN}InfoVersionTTN"/>
 *         &lt;element name="QueryBarcode" type="{http://fsrar.ru/WEGAIS/QueryBarcode}QueryBarcode"/>
 *         &lt;element name="ReplyBarcode" type="{http://fsrar.ru/WEGAIS/ReplyBarcode}ReplyBarcode"/>
 *         &lt;element name="RequestRepealWB" type="{http://fsrar.ru/WEGAIS/RequestRepealWB}RequestRepealWB"/>
 *         &lt;element name="ConfirmRepealWB" type="{http://fsrar.ru/WEGAIS/ConfirmRepealWB}ConfirmRepealWB"/>
 *         &lt;element name="RequestRepealACO" type="{http://fsrar.ru/WEGAIS/RequestRepealACO}RequestRepealACO"/>
 *         &lt;element name="RequestRepealAWO" type="{http://fsrar.ru/WEGAIS/RequestRepealAWO}RequestRepealAWO"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocBody", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01", propOrder = {
    "wayBill",
    "ticket",
    "wayBillAct",
    "confirmTicket",
    "ttnInformBReg",
    "actInventory",
    "actChargeOn",
    "actInventoryInformBReg",
    "queryAP",
    "querySSP",
    "querySP",
    "queryClients",
    "queryClientVersion",
    "queryRests",
    "queryFormBHistory",
    "queryResendDoc",
    "queryFormA",
    "queryFormB",
    "actWriteOff",
    "repProducedProduct",
    "repImportedProduct",
    "replySSP",
    "replySpirit",
    "replyClient",
    "replyAP",
    "replyRests",
    "replyFormA",
    "replyFormB",
    "replyHistFormB",
    "replyClientVersion",
    "queryRejectRepProduced",
    "queryRejectRepImported",
    "replySSPV2",
    "replySpiritV2",
    "replyClientV2",
    "replyAPV2",
    "replyRestsV2",
    "replyForm1",
    "replyForm2",
    "replyHistForm2",
    "wayBillV2",
    "wayBillActV2",
    "actChargeOnV2",
    "actInventoryInformF2Reg",
    "ttnInformF2Reg",
    "queryAPV2",
    "querySSPV2",
    "querySPV2",
    "queryClientsV2",
    "queryRestsV2",
    "queryFormF1",
    "queryFormF2",
    "actWriteOffV2",
    "transferFromShop",
    "transferToShop",
    "queryForm2History",
    "repInformF1Reg",
    "replyNoAnswerTTN",
    "queryNATTN",
    "queryRestsShopV2",
    "replyRestsShopV2",
    "asiiu",
    "asiiuTime",
    "actChargeOnShopV2",
    "actWriteOffShopV2",
    "infoVersionTTN",
    "queryBarcode",
    "replyBarcode",
    "requestRepealWB",
    "confirmRepealWB",
    "requestRepealACO",
    "requestRepealAWO"
})
public class DocBody {

    @XmlElement(name = "WayBill", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillType wayBill;
    @XmlElement(name = "Ticket", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected TicketType ticket;
    @XmlElement(name = "WayBillAct", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillActType wayBillAct;
    @XmlElement(name = "ConfirmTicket", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ConfirmTicketType confirmTicket;
    @XmlElement(name = "TTNInformBReg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillInformBRegType ttnInformBReg;
    @XmlElement(name = "ActInventory", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActInventoryType actInventory;
    @XmlElement(name = "ActChargeOn", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActChargeOnType actChargeOn;
    @XmlElement(name = "ActInventoryInformBReg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActInventoryInformBReg actInventoryInformBReg;
    @XmlElement(name = "QueryAP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryAP;
    @XmlElement(name = "QuerySSP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters querySSP;
    @XmlElement(name = "QuerySP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters querySP;
    @XmlElement(name = "QueryClients", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryClients;
    @XmlElement(name = "QueryClientVersion", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryClientVersion;
    @XmlElement(name = "QueryRests", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryRests;
    @XmlElement(name = "QueryFormBHistory", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryFormBHistory;
    @XmlElement(name = "QueryResendDoc", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryResendDoc;
    @XmlElement(name = "QueryFormA", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryFormAB queryFormA;
    @XmlElement(name = "QueryFormB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryFormAB queryFormB;
    @XmlElement(name = "ActWriteOff", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActWriteOffType actWriteOff;
    @XmlElement(name = "RepProducedProduct", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RepProducedType repProducedProduct;
    @XmlElement(name = "RepImportedProduct", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RepImportedType repImportedProduct;
    @XmlElement(name = "ReplySSP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplySSP replySSP;
    @XmlElement(name = "ReplySpirit", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplySpirit replySpirit;
    @XmlElement(name = "ReplyClient", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyClient replyClient;
    @XmlElement(name = "ReplyAP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyAP replyAP;
    @XmlElement(name = "ReplyRests", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyRests replyRests;
    @XmlElement(name = "ReplyFormA", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyFormA replyFormA;
    @XmlElement(name = "ReplyFormB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyFormB replyFormB;
    @XmlElement(name = "ReplyHistFormB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyHistFormB replyHistFormB;
    @XmlElement(name = "ReplyClientVersion", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyClientVersion replyClientVersion;
    @XmlElement(name = "QueryRejectRepProduced", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryRejectRepProduced queryRejectRepProduced;
    @XmlElement(name = "QueryRejectRepImported", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryRejectRepImported queryRejectRepImported;
    @XmlElement(name = "ReplySSP_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplySSPV2 replySSPV2;
    @XmlElement(name = "ReplySpirit_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplySpiritV2 replySpiritV2;
    @XmlElement(name = "ReplyClient_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyClientV2 replyClientV2;
    @XmlElement(name = "ReplyAP_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyAPV2 replyAPV2;
    @XmlElement(name = "ReplyRests_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyRestsV2 replyRestsV2;
    @XmlElement(name = "ReplyForm1", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyForm1 replyForm1;
    @XmlElement(name = "ReplyForm2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyForm2 replyForm2;
    @XmlElement(name = "ReplyHistForm2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyHistForm2 replyHistForm2;
    @XmlElement(name = "WayBill_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillTypeV2 wayBillV2;
    @XmlElement(name = "WayBillAct_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillActTypeV2 wayBillActV2;
    @XmlElement(name = "ActChargeOn_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActChargeOnTypeV2 actChargeOnV2;
    @XmlElement(name = "ActInventoryInformF2Reg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActInventoryInformF2Reg actInventoryInformF2Reg;
    @XmlElement(name = "TTNInformF2Reg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected WayBillInformF2RegType ttnInformF2Reg;
    @XmlElement(name = "QueryAP_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryAPV2;
    @XmlElement(name = "QuerySSP_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters querySSPV2;
    @XmlElement(name = "QuerySP_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters querySPV2;
    @XmlElement(name = "QueryClients_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryClientsV2;
    @XmlElement(name = "QueryRests_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryRestsV2;
    @XmlElement(name = "QueryFormF1", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryFormF1F2 queryFormF1;
    @XmlElement(name = "QueryFormF2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryFormF1F2 queryFormF2;
    @XmlElement(name = "ActWriteOff_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActWriteOffTypeV2 actWriteOffV2;
    @XmlElement(name = "TransferFromShop", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected TransferFromShopType transferFromShop;
    @XmlElement(name = "TransferToShop", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected TransferToShopType transferToShop;
    @XmlElement(name = "QueryForm2History", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryForm2History;
    @XmlElement(name = "RepInformF1Reg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RepPIInformF1RegType repInformF1Reg;
    @XmlElement(name = "ReplyNoAnswerTTN", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected NoAnswerTTN replyNoAnswerTTN;
    @XmlElement(name = "QueryNATTN", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryNATTN;
    @XmlElement(name = "QueryRestsShop_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryParameters queryRestsShopV2;
    @XmlElement(name = "ReplyRestsShop_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyRestsShopV2 replyRestsShopV2;
    @XmlElement(name = "Asiiu", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected Asiiu asiiu;
    @XmlElement(name = "AsiiuTime", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected AsiiuTime asiiuTime;
    @XmlElement(name = "ActChargeOnShop_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActChargeOnShopTypeV2 actChargeOnShopV2;
    @XmlElement(name = "ActWriteOffShop_v2", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ActWriteOffShopTypeV2 actWriteOffShopV2;
    @XmlElement(name = "InfoVersionTTN", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected InfoVersionTTN infoVersionTTN;
    @XmlElement(name = "QueryBarcode", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected QueryBarcode queryBarcode;
    @XmlElement(name = "ReplyBarcode", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ReplyBarcode replyBarcode;
    @XmlElement(name = "RequestRepealWB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RequestRepealWB requestRepealWB;
    @XmlElement(name = "ConfirmRepealWB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected ConfirmRepealWB confirmRepealWB;
    @XmlElement(name = "RequestRepealACO", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RequestRepealACO requestRepealACO;
    @XmlElement(name = "RequestRepealAWO", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
    protected RequestRepealAWO requestRepealAWO;

    /**
     * Gets the value of the wayBill property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillType }
     *     
     */
    public WayBillType getWayBill() {
        return wayBill;
    }

    /**
     * Sets the value of the wayBill property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillType }
     *     
     */
    public void setWayBill(WayBillType value) {
        this.wayBill = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link TicketType }
     *     
     */
    public TicketType getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketType }
     *     
     */
    public void setTicket(TicketType value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the wayBillAct property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillActType }
     *     
     */
    public WayBillActType getWayBillAct() {
        return wayBillAct;
    }

    /**
     * Sets the value of the wayBillAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillActType }
     *     
     */
    public void setWayBillAct(WayBillActType value) {
        this.wayBillAct = value;
    }

    /**
     * Gets the value of the confirmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link ConfirmTicketType }
     *     
     */
    public ConfirmTicketType getConfirmTicket() {
        return confirmTicket;
    }

    /**
     * Sets the value of the confirmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfirmTicketType }
     *     
     */
    public void setConfirmTicket(ConfirmTicketType value) {
        this.confirmTicket = value;
    }

    /**
     * Gets the value of the ttnInformBReg property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillInformBRegType }
     *     
     */
    public WayBillInformBRegType getTTNInformBReg() {
        return ttnInformBReg;
    }

    /**
     * Sets the value of the ttnInformBReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillInformBRegType }
     *     
     */
    public void setTTNInformBReg(WayBillInformBRegType value) {
        this.ttnInformBReg = value;
    }

    /**
     * Gets the value of the actInventory property.
     * 
     * @return
     *     possible object is
     *     {@link ActInventoryType }
     *     
     */
    public ActInventoryType getActInventory() {
        return actInventory;
    }

    /**
     * Sets the value of the actInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActInventoryType }
     *     
     */
    public void setActInventory(ActInventoryType value) {
        this.actInventory = value;
    }

    /**
     * Gets the value of the actChargeOn property.
     * 
     * @return
     *     possible object is
     *     {@link ActChargeOnType }
     *     
     */
    public ActChargeOnType getActChargeOn() {
        return actChargeOn;
    }

    /**
     * Sets the value of the actChargeOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActChargeOnType }
     *     
     */
    public void setActChargeOn(ActChargeOnType value) {
        this.actChargeOn = value;
    }

    /**
     * Gets the value of the actInventoryInformBReg property.
     * 
     * @return
     *     possible object is
     *     {@link ActInventoryInformBReg }
     *     
     */
    public ActInventoryInformBReg getActInventoryInformBReg() {
        return actInventoryInformBReg;
    }

    /**
     * Sets the value of the actInventoryInformBReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActInventoryInformBReg }
     *     
     */
    public void setActInventoryInformBReg(ActInventoryInformBReg value) {
        this.actInventoryInformBReg = value;
    }

    /**
     * Gets the value of the queryAP property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryAP() {
        return queryAP;
    }

    /**
     * Sets the value of the queryAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryAP(QueryParameters value) {
        this.queryAP = value;
    }

    /**
     * Gets the value of the querySSP property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQuerySSP() {
        return querySSP;
    }

    /**
     * Sets the value of the querySSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQuerySSP(QueryParameters value) {
        this.querySSP = value;
    }

    /**
     * Gets the value of the querySP property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQuerySP() {
        return querySP;
    }

    /**
     * Sets the value of the querySP property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQuerySP(QueryParameters value) {
        this.querySP = value;
    }

    /**
     * Gets the value of the queryClients property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryClients() {
        return queryClients;
    }

    /**
     * Sets the value of the queryClients property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryClients(QueryParameters value) {
        this.queryClients = value;
    }

    /**
     * Gets the value of the queryClientVersion property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryClientVersion() {
        return queryClientVersion;
    }

    /**
     * Sets the value of the queryClientVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryClientVersion(QueryParameters value) {
        this.queryClientVersion = value;
    }

    /**
     * Gets the value of the queryRests property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryRests() {
        return queryRests;
    }

    /**
     * Sets the value of the queryRests property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryRests(QueryParameters value) {
        this.queryRests = value;
    }

    /**
     * Gets the value of the queryFormBHistory property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryFormBHistory() {
        return queryFormBHistory;
    }

    /**
     * Sets the value of the queryFormBHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryFormBHistory(QueryParameters value) {
        this.queryFormBHistory = value;
    }

    /**
     * Gets the value of the queryResendDoc property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryResendDoc() {
        return queryResendDoc;
    }

    /**
     * Sets the value of the queryResendDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryResendDoc(QueryParameters value) {
        this.queryResendDoc = value;
    }

    /**
     * Gets the value of the queryFormA property.
     * 
     * @return
     *     possible object is
     *     {@link QueryFormAB }
     *     
     */
    public QueryFormAB getQueryFormA() {
        return queryFormA;
    }

    /**
     * Sets the value of the queryFormA property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryFormAB }
     *     
     */
    public void setQueryFormA(QueryFormAB value) {
        this.queryFormA = value;
    }

    /**
     * Gets the value of the queryFormB property.
     * 
     * @return
     *     possible object is
     *     {@link QueryFormAB }
     *     
     */
    public QueryFormAB getQueryFormB() {
        return queryFormB;
    }

    /**
     * Sets the value of the queryFormB property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryFormAB }
     *     
     */
    public void setQueryFormB(QueryFormAB value) {
        this.queryFormB = value;
    }

    /**
     * Gets the value of the actWriteOff property.
     * 
     * @return
     *     possible object is
     *     {@link ActWriteOffType }
     *     
     */
    public ActWriteOffType getActWriteOff() {
        return actWriteOff;
    }

    /**
     * Sets the value of the actWriteOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWriteOffType }
     *     
     */
    public void setActWriteOff(ActWriteOffType value) {
        this.actWriteOff = value;
    }

    /**
     * Gets the value of the repProducedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link RepProducedType }
     *     
     */
    public RepProducedType getRepProducedProduct() {
        return repProducedProduct;
    }

    /**
     * Sets the value of the repProducedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepProducedType }
     *     
     */
    public void setRepProducedProduct(RepProducedType value) {
        this.repProducedProduct = value;
    }

    /**
     * Gets the value of the repImportedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link RepImportedType }
     *     
     */
    public RepImportedType getRepImportedProduct() {
        return repImportedProduct;
    }

    /**
     * Sets the value of the repImportedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepImportedType }
     *     
     */
    public void setRepImportedProduct(RepImportedType value) {
        this.repImportedProduct = value;
    }

    /**
     * Gets the value of the replySSP property.
     * 
     * @return
     *     possible object is
     *     {@link ReplySSP }
     *     
     */
    public ReplySSP getReplySSP() {
        return replySSP;
    }

    /**
     * Sets the value of the replySSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplySSP }
     *     
     */
    public void setReplySSP(ReplySSP value) {
        this.replySSP = value;
    }

    /**
     * Gets the value of the replySpirit property.
     * 
     * @return
     *     possible object is
     *     {@link ReplySpirit }
     *     
     */
    public ReplySpirit getReplySpirit() {
        return replySpirit;
    }

    /**
     * Sets the value of the replySpirit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplySpirit }
     *     
     */
    public void setReplySpirit(ReplySpirit value) {
        this.replySpirit = value;
    }

    /**
     * Gets the value of the replyClient property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyClient }
     *     
     */
    public ReplyClient getReplyClient() {
        return replyClient;
    }

    /**
     * Sets the value of the replyClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyClient }
     *     
     */
    public void setReplyClient(ReplyClient value) {
        this.replyClient = value;
    }

    /**
     * Gets the value of the replyAP property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyAP }
     *     
     */
    public ReplyAP getReplyAP() {
        return replyAP;
    }

    /**
     * Sets the value of the replyAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyAP }
     *     
     */
    public void setReplyAP(ReplyAP value) {
        this.replyAP = value;
    }

    /**
     * Gets the value of the replyRests property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyRests }
     *     
     */
    public ReplyRests getReplyRests() {
        return replyRests;
    }

    /**
     * Sets the value of the replyRests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyRests }
     *     
     */
    public void setReplyRests(ReplyRests value) {
        this.replyRests = value;
    }

    /**
     * Gets the value of the replyFormA property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyFormA }
     *     
     */
    public ReplyFormA getReplyFormA() {
        return replyFormA;
    }

    /**
     * Sets the value of the replyFormA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyFormA }
     *     
     */
    public void setReplyFormA(ReplyFormA value) {
        this.replyFormA = value;
    }

    /**
     * Gets the value of the replyFormB property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyFormB }
     *     
     */
    public ReplyFormB getReplyFormB() {
        return replyFormB;
    }

    /**
     * Sets the value of the replyFormB property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyFormB }
     *     
     */
    public void setReplyFormB(ReplyFormB value) {
        this.replyFormB = value;
    }

    /**
     * Gets the value of the replyHistFormB property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyHistFormB }
     *     
     */
    public ReplyHistFormB getReplyHistFormB() {
        return replyHistFormB;
    }

    /**
     * Sets the value of the replyHistFormB property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyHistFormB }
     *     
     */
    public void setReplyHistFormB(ReplyHistFormB value) {
        this.replyHistFormB = value;
    }

    /**
     * Gets the value of the replyClientVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyClientVersion }
     *     
     */
    public ReplyClientVersion getReplyClientVersion() {
        return replyClientVersion;
    }

    /**
     * Sets the value of the replyClientVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyClientVersion }
     *     
     */
    public void setReplyClientVersion(ReplyClientVersion value) {
        this.replyClientVersion = value;
    }

    /**
     * Gets the value of the queryRejectRepProduced property.
     * 
     * @return
     *     possible object is
     *     {@link QueryRejectRepProduced }
     *     
     */
    public QueryRejectRepProduced getQueryRejectRepProduced() {
        return queryRejectRepProduced;
    }

    /**
     * Sets the value of the queryRejectRepProduced property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryRejectRepProduced }
     *     
     */
    public void setQueryRejectRepProduced(QueryRejectRepProduced value) {
        this.queryRejectRepProduced = value;
    }

    /**
     * Gets the value of the queryRejectRepImported property.
     * 
     * @return
     *     possible object is
     *     {@link QueryRejectRepImported }
     *     
     */
    public QueryRejectRepImported getQueryRejectRepImported() {
        return queryRejectRepImported;
    }

    /**
     * Sets the value of the queryRejectRepImported property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryRejectRepImported }
     *     
     */
    public void setQueryRejectRepImported(QueryRejectRepImported value) {
        this.queryRejectRepImported = value;
    }

    /**
     * Gets the value of the replySSPV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplySSPV2 }
     *     
     */
    public ReplySSPV2 getReplySSPV2() {
        return replySSPV2;
    }

    /**
     * Sets the value of the replySSPV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplySSPV2 }
     *     
     */
    public void setReplySSPV2(ReplySSPV2 value) {
        this.replySSPV2 = value;
    }

    /**
     * Gets the value of the replySpiritV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplySpiritV2 }
     *     
     */
    public ReplySpiritV2 getReplySpiritV2() {
        return replySpiritV2;
    }

    /**
     * Sets the value of the replySpiritV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplySpiritV2 }
     *     
     */
    public void setReplySpiritV2(ReplySpiritV2 value) {
        this.replySpiritV2 = value;
    }

    /**
     * Gets the value of the replyClientV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyClientV2 }
     *     
     */
    public ReplyClientV2 getReplyClientV2() {
        return replyClientV2;
    }

    /**
     * Sets the value of the replyClientV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyClientV2 }
     *     
     */
    public void setReplyClientV2(ReplyClientV2 value) {
        this.replyClientV2 = value;
    }

    /**
     * Gets the value of the replyAPV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyAPV2 }
     *     
     */
    public ReplyAPV2 getReplyAPV2() {
        return replyAPV2;
    }

    /**
     * Sets the value of the replyAPV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyAPV2 }
     *     
     */
    public void setReplyAPV2(ReplyAPV2 value) {
        this.replyAPV2 = value;
    }

    /**
     * Gets the value of the replyRestsV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyRestsV2 }
     *     
     */
    public ReplyRestsV2 getReplyRestsV2() {
        return replyRestsV2;
    }

    /**
     * Sets the value of the replyRestsV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyRestsV2 }
     *     
     */
    public void setReplyRestsV2(ReplyRestsV2 value) {
        this.replyRestsV2 = value;
    }

    /**
     * Gets the value of the replyForm1 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyForm1 }
     *     
     */
    public ReplyForm1 getReplyForm1() {
        return replyForm1;
    }

    /**
     * Sets the value of the replyForm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyForm1 }
     *     
     */
    public void setReplyForm1(ReplyForm1 value) {
        this.replyForm1 = value;
    }

    /**
     * Gets the value of the replyForm2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyForm2 }
     *     
     */
    public ReplyForm2 getReplyForm2() {
        return replyForm2;
    }

    /**
     * Sets the value of the replyForm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyForm2 }
     *     
     */
    public void setReplyForm2(ReplyForm2 value) {
        this.replyForm2 = value;
    }

    /**
     * Gets the value of the replyHistForm2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyHistForm2 }
     *     
     */
    public ReplyHistForm2 getReplyHistForm2() {
        return replyHistForm2;
    }

    /**
     * Sets the value of the replyHistForm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyHistForm2 }
     *     
     */
    public void setReplyHistForm2(ReplyHistForm2 value) {
        this.replyHistForm2 = value;
    }

    /**
     * Gets the value of the wayBillV2 property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillTypeV2 }
     *     
     */
    public WayBillTypeV2 getWayBillV2() {
        return wayBillV2;
    }

    /**
     * Sets the value of the wayBillV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillTypeV2 }
     *     
     */
    public void setWayBillV2(WayBillTypeV2 value) {
        this.wayBillV2 = value;
    }

    /**
     * Gets the value of the wayBillActV2 property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillActTypeV2 }
     *     
     */
    public WayBillActTypeV2 getWayBillActV2() {
        return wayBillActV2;
    }

    /**
     * Sets the value of the wayBillActV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillActTypeV2 }
     *     
     */
    public void setWayBillActV2(WayBillActTypeV2 value) {
        this.wayBillActV2 = value;
    }

    /**
     * Gets the value of the actChargeOnV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActChargeOnTypeV2 }
     *     
     */
    public ActChargeOnTypeV2 getActChargeOnV2() {
        return actChargeOnV2;
    }

    /**
     * Sets the value of the actChargeOnV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActChargeOnTypeV2 }
     *     
     */
    public void setActChargeOnV2(ActChargeOnTypeV2 value) {
        this.actChargeOnV2 = value;
    }

    /**
     * Gets the value of the actInventoryInformF2Reg property.
     * 
     * @return
     *     possible object is
     *     {@link ActInventoryInformF2Reg }
     *     
     */
    public ActInventoryInformF2Reg getActInventoryInformF2Reg() {
        return actInventoryInformF2Reg;
    }

    /**
     * Sets the value of the actInventoryInformF2Reg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActInventoryInformF2Reg }
     *     
     */
    public void setActInventoryInformF2Reg(ActInventoryInformF2Reg value) {
        this.actInventoryInformF2Reg = value;
    }

    /**
     * Gets the value of the ttnInformF2Reg property.
     * 
     * @return
     *     possible object is
     *     {@link WayBillInformF2RegType }
     *     
     */
    public WayBillInformF2RegType getTTNInformF2Reg() {
        return ttnInformF2Reg;
    }

    /**
     * Sets the value of the ttnInformF2Reg property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayBillInformF2RegType }
     *     
     */
    public void setTTNInformF2Reg(WayBillInformF2RegType value) {
        this.ttnInformF2Reg = value;
    }

    /**
     * Gets the value of the queryAPV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryAPV2() {
        return queryAPV2;
    }

    /**
     * Sets the value of the queryAPV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryAPV2(QueryParameters value) {
        this.queryAPV2 = value;
    }

    /**
     * Gets the value of the querySSPV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQuerySSPV2() {
        return querySSPV2;
    }

    /**
     * Sets the value of the querySSPV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQuerySSPV2(QueryParameters value) {
        this.querySSPV2 = value;
    }

    /**
     * Gets the value of the querySPV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQuerySPV2() {
        return querySPV2;
    }

    /**
     * Sets the value of the querySPV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQuerySPV2(QueryParameters value) {
        this.querySPV2 = value;
    }

    /**
     * Gets the value of the queryClientsV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryClientsV2() {
        return queryClientsV2;
    }

    /**
     * Sets the value of the queryClientsV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryClientsV2(QueryParameters value) {
        this.queryClientsV2 = value;
    }

    /**
     * Gets the value of the queryRestsV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryRestsV2() {
        return queryRestsV2;
    }

    /**
     * Sets the value of the queryRestsV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryRestsV2(QueryParameters value) {
        this.queryRestsV2 = value;
    }

    /**
     * Gets the value of the queryFormF1 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryFormF1F2 }
     *     
     */
    public QueryFormF1F2 getQueryFormF1() {
        return queryFormF1;
    }

    /**
     * Sets the value of the queryFormF1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryFormF1F2 }
     *     
     */
    public void setQueryFormF1(QueryFormF1F2 value) {
        this.queryFormF1 = value;
    }

    /**
     * Gets the value of the queryFormF2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryFormF1F2 }
     *     
     */
    public QueryFormF1F2 getQueryFormF2() {
        return queryFormF2;
    }

    /**
     * Sets the value of the queryFormF2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryFormF1F2 }
     *     
     */
    public void setQueryFormF2(QueryFormF1F2 value) {
        this.queryFormF2 = value;
    }

    /**
     * Gets the value of the actWriteOffV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActWriteOffTypeV2 }
     *     
     */
    public ActWriteOffTypeV2 getActWriteOffV2() {
        return actWriteOffV2;
    }

    /**
     * Sets the value of the actWriteOffV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWriteOffTypeV2 }
     *     
     */
    public void setActWriteOffV2(ActWriteOffTypeV2 value) {
        this.actWriteOffV2 = value;
    }

    /**
     * Gets the value of the transferFromShop property.
     * 
     * @return
     *     possible object is
     *     {@link TransferFromShopType }
     *     
     */
    public TransferFromShopType getTransferFromShop() {
        return transferFromShop;
    }

    /**
     * Sets the value of the transferFromShop property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferFromShopType }
     *     
     */
    public void setTransferFromShop(TransferFromShopType value) {
        this.transferFromShop = value;
    }

    /**
     * Gets the value of the transferToShop property.
     * 
     * @return
     *     possible object is
     *     {@link TransferToShopType }
     *     
     */
    public TransferToShopType getTransferToShop() {
        return transferToShop;
    }

    /**
     * Sets the value of the transferToShop property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferToShopType }
     *     
     */
    public void setTransferToShop(TransferToShopType value) {
        this.transferToShop = value;
    }

    /**
     * Gets the value of the queryForm2History property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryForm2History() {
        return queryForm2History;
    }

    /**
     * Sets the value of the queryForm2History property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryForm2History(QueryParameters value) {
        this.queryForm2History = value;
    }

    /**
     * Gets the value of the repInformF1Reg property.
     * 
     * @return
     *     possible object is
     *     {@link RepPIInformF1RegType }
     *     
     */
    public RepPIInformF1RegType getRepInformF1Reg() {
        return repInformF1Reg;
    }

    /**
     * Sets the value of the repInformF1Reg property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepPIInformF1RegType }
     *     
     */
    public void setRepInformF1Reg(RepPIInformF1RegType value) {
        this.repInformF1Reg = value;
    }

    /**
     * Gets the value of the replyNoAnswerTTN property.
     * 
     * @return
     *     possible object is
     *     {@link NoAnswerTTN }
     *     
     */
    public NoAnswerTTN getReplyNoAnswerTTN() {
        return replyNoAnswerTTN;
    }

    /**
     * Sets the value of the replyNoAnswerTTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoAnswerTTN }
     *     
     */
    public void setReplyNoAnswerTTN(NoAnswerTTN value) {
        this.replyNoAnswerTTN = value;
    }

    /**
     * Gets the value of the queryNATTN property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryNATTN() {
        return queryNATTN;
    }

    /**
     * Sets the value of the queryNATTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryNATTN(QueryParameters value) {
        this.queryNATTN = value;
    }

    /**
     * Gets the value of the queryRestsShopV2 property.
     * 
     * @return
     *     possible object is
     *     {@link QueryParameters }
     *     
     */
    public QueryParameters getQueryRestsShopV2() {
        return queryRestsShopV2;
    }

    /**
     * Sets the value of the queryRestsShopV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryParameters }
     *     
     */
    public void setQueryRestsShopV2(QueryParameters value) {
        this.queryRestsShopV2 = value;
    }

    /**
     * Gets the value of the replyRestsShopV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyRestsShopV2 }
     *     
     */
    public ReplyRestsShopV2 getReplyRestsShopV2() {
        return replyRestsShopV2;
    }

    /**
     * Sets the value of the replyRestsShopV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyRestsShopV2 }
     *     
     */
    public void setReplyRestsShopV2(ReplyRestsShopV2 value) {
        this.replyRestsShopV2 = value;
    }

    /**
     * Gets the value of the asiiu property.
     * 
     * @return
     *     possible object is
     *     {@link Asiiu }
     *     
     */
    public Asiiu getAsiiu() {
        return asiiu;
    }

    /**
     * Sets the value of the asiiu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asiiu }
     *     
     */
    public void setAsiiu(Asiiu value) {
        this.asiiu = value;
    }

    /**
     * Gets the value of the asiiuTime property.
     * 
     * @return
     *     possible object is
     *     {@link AsiiuTime }
     *     
     */
    public AsiiuTime getAsiiuTime() {
        return asiiuTime;
    }

    /**
     * Sets the value of the asiiuTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsiiuTime }
     *     
     */
    public void setAsiiuTime(AsiiuTime value) {
        this.asiiuTime = value;
    }

    /**
     * Gets the value of the actChargeOnShopV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActChargeOnShopTypeV2 }
     *     
     */
    public ActChargeOnShopTypeV2 getActChargeOnShopV2() {
        return actChargeOnShopV2;
    }

    /**
     * Sets the value of the actChargeOnShopV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActChargeOnShopTypeV2 }
     *     
     */
    public void setActChargeOnShopV2(ActChargeOnShopTypeV2 value) {
        this.actChargeOnShopV2 = value;
    }

    /**
     * Gets the value of the actWriteOffShopV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActWriteOffShopTypeV2 }
     *     
     */
    public ActWriteOffShopTypeV2 getActWriteOffShopV2() {
        return actWriteOffShopV2;
    }

    /**
     * Sets the value of the actWriteOffShopV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWriteOffShopTypeV2 }
     *     
     */
    public void setActWriteOffShopV2(ActWriteOffShopTypeV2 value) {
        this.actWriteOffShopV2 = value;
    }

    /**
     * Gets the value of the infoVersionTTN property.
     * 
     * @return
     *     possible object is
     *     {@link InfoVersionTTN }
     *     
     */
    public InfoVersionTTN getInfoVersionTTN() {
        return infoVersionTTN;
    }

    /**
     * Sets the value of the infoVersionTTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoVersionTTN }
     *     
     */
    public void setInfoVersionTTN(InfoVersionTTN value) {
        this.infoVersionTTN = value;
    }

    /**
     * Gets the value of the queryBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link QueryBarcode }
     *     
     */
    public QueryBarcode getQueryBarcode() {
        return queryBarcode;
    }

    /**
     * Sets the value of the queryBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryBarcode }
     *     
     */
    public void setQueryBarcode(QueryBarcode value) {
        this.queryBarcode = value;
    }

    /**
     * Gets the value of the replyBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyBarcode }
     *     
     */
    public ReplyBarcode getReplyBarcode() {
        return replyBarcode;
    }

    /**
     * Sets the value of the replyBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyBarcode }
     *     
     */
    public void setReplyBarcode(ReplyBarcode value) {
        this.replyBarcode = value;
    }

    /**
     * Gets the value of the requestRepealWB property.
     * 
     * @return
     *     possible object is
     *     {@link RequestRepealWB }
     *     
     */
    public RequestRepealWB getRequestRepealWB() {
        return requestRepealWB;
    }

    /**
     * Sets the value of the requestRepealWB property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestRepealWB }
     *     
     */
    public void setRequestRepealWB(RequestRepealWB value) {
        this.requestRepealWB = value;
    }

    /**
     * Gets the value of the confirmRepealWB property.
     * 
     * @return
     *     possible object is
     *     {@link ConfirmRepealWB }
     *     
     */
    public ConfirmRepealWB getConfirmRepealWB() {
        return confirmRepealWB;
    }

    /**
     * Sets the value of the confirmRepealWB property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfirmRepealWB }
     *     
     */
    public void setConfirmRepealWB(ConfirmRepealWB value) {
        this.confirmRepealWB = value;
    }

    /**
     * Gets the value of the requestRepealACO property.
     * 
     * @return
     *     possible object is
     *     {@link RequestRepealACO }
     *     
     */
    public RequestRepealACO getRequestRepealACO() {
        return requestRepealACO;
    }

    /**
     * Sets the value of the requestRepealACO property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestRepealACO }
     *     
     */
    public void setRequestRepealACO(RequestRepealACO value) {
        this.requestRepealACO = value;
    }

    /**
     * Gets the value of the requestRepealAWO property.
     * 
     * @return
     *     possible object is
     *     {@link RequestRepealAWO }
     *     
     */
    public RequestRepealAWO getRequestRepealAWO() {
        return requestRepealAWO;
    }

    /**
     * Sets the value of the requestRepealAWO property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestRepealAWO }
     *     
     */
    public void setRequestRepealAWO(RequestRepealAWO value) {
        this.requestRepealAWO = value;
    }

}
