//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:12:18 PM MSK 
//


package ru.crystals.pos.egais.documents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Справки А и Б документы
 * 
 * <p>Java class for InformABRegType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformABRegType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InformA" type="{http://fsrar.ru/WEGAIS/ActInventoryABInfo}InformARegType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformABRegType", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn", propOrder = {
    "informA"
})
public class InformABRegType {

    @XmlElement(name = "InformA", namespace = "http://fsrar.ru/WEGAIS/ActChargeOn", required = true)
    protected InformARegType informA;

    /**
     * Gets the value of the informA property.
     * 
     * @return
     *     possible object is
     *     {@link InformARegType }
     *     
     */
    public InformARegType getInformA() {
        return informA;
    }

    /**
     * Sets the value of the informA property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformARegType }
     *     
     */
    public void setInformA(InformARegType value) {
        this.informA = value;
    }

}
