//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:12:18 PM MSK 
//


package ru.crystals.pos.egais.documents;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.crystals.pos.egais.documents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrgInfoINN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "INN");
    private final static QName _OrgInfoRNN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "RNN");
    private final static QName _OrgInfoUNP_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "UNP");
    private final static QName _OrgInfoExState_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "State");
    private final static QName _TSReplyTypeTSNUM_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "TSNUM");
    private final static QName _OrgInfoExV2State_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "State");
    private final static QName _OrgInfoExV2VersionWB_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "VersionWB");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.crystals.pos.egais.documents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfirmRepealWB }
     * 
     */
    public ConfirmRepealWB createConfirmRepealWB() {
        return new ConfirmRepealWB();
    }

    /**
     * Create an instance of {@link ReplyBarcode }
     * 
     */
    public ReplyBarcode createReplyBarcode() {
        return new ReplyBarcode();
    }

    /**
     * Create an instance of {@link QueryBarcode }
     * 
     */
    public QueryBarcode createQueryBarcode() {
        return new QueryBarcode();
    }

    /**
     * Create an instance of {@link ActWriteOffShopTypeV2 }
     * 
     */
    public ActWriteOffShopTypeV2 createActWriteOffShopTypeV2() {
        return new ActWriteOffShopTypeV2();
    }

    /**
     * Create an instance of {@link ActChargeOnShopTypeV2 }
     * 
     */
    public ActChargeOnShopTypeV2 createActChargeOnShopTypeV2() {
        return new ActChargeOnShopTypeV2();
    }

    /**
     * Create an instance of {@link AsiiuTime }
     * 
     */
    public AsiiuTime createAsiiuTime() {
        return new AsiiuTime();
    }

    /**
     * Create an instance of {@link Asiiu }
     * 
     */
    public Asiiu createAsiiu() {
        return new Asiiu();
    }

    /**
     * Create an instance of {@link ReplyRestsShopV2 }
     * 
     */
    public ReplyRestsShopV2 createReplyRestsShopV2() {
        return new ReplyRestsShopV2();
    }

    /**
     * Create an instance of {@link NoAnswerTTN }
     * 
     */
    public NoAnswerTTN createNoAnswerTTN() {
        return new NoAnswerTTN();
    }

    /**
     * Create an instance of {@link RepPIInformF1RegType }
     * 
     */
    public RepPIInformF1RegType createRepPIInformF1RegType() {
        return new RepPIInformF1RegType();
    }

    /**
     * Create an instance of {@link TransferToShopType }
     * 
     */
    public TransferToShopType createTransferToShopType() {
        return new TransferToShopType();
    }

    /**
     * Create an instance of {@link TransferFromShopType }
     * 
     */
    public TransferFromShopType createTransferFromShopType() {
        return new TransferFromShopType();
    }

    /**
     * Create an instance of {@link ActWriteOffTypeV2 }
     * 
     */
    public ActWriteOffTypeV2 createActWriteOffTypeV2() {
        return new ActWriteOffTypeV2();
    }

    /**
     * Create an instance of {@link WayBillInformF2RegType }
     * 
     */
    public WayBillInformF2RegType createWayBillInformF2RegType() {
        return new WayBillInformF2RegType();
    }

    /**
     * Create an instance of {@link InformInvPositionType2 }
     * 
     */
    public InformInvPositionType2 createInformInvPositionType2() {
        return new InformInvPositionType2();
    }

    /**
     * Create an instance of {@link ActInventoryInformF2Reg }
     * 
     */
    public ActInventoryInformF2Reg createActInventoryInformF2Reg() {
        return new ActInventoryInformF2Reg();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType2 }
     * 
     */
    public ActChargeOnPositionType2 createActChargeOnPositionType2() {
        return new ActChargeOnPositionType2();
    }

    /**
     * Create an instance of {@link ActChargeOnTypeV2 }
     * 
     */
    public ActChargeOnTypeV2 createActChargeOnTypeV2() {
        return new ActChargeOnTypeV2();
    }

    /**
     * Create an instance of {@link WayBillActTypeV2 }
     * 
     */
    public WayBillActTypeV2 createWayBillActTypeV2() {
        return new WayBillActTypeV2();
    }

    /**
     * Create an instance of {@link WayBillTypeV2 }
     * 
     */
    public WayBillTypeV2 createWayBillTypeV2() {
        return new WayBillTypeV2();
    }

    /**
     * Create an instance of {@link ReplyHistForm2 }
     * 
     */
    public ReplyHistForm2 createReplyHistForm2() {
        return new ReplyHistForm2();
    }

    /**
     * Create an instance of {@link ReplyRestsV2 }
     * 
     */
    public ReplyRestsV2 createReplyRestsV2() {
        return new ReplyRestsV2();
    }

    /**
     * Create an instance of {@link ReplyAPV2 }
     * 
     */
    public ReplyAPV2 createReplyAPV2() {
        return new ReplyAPV2();
    }

    /**
     * Create an instance of {@link ReplyClientV2 }
     * 
     */
    public ReplyClientV2 createReplyClientV2() {
        return new ReplyClientV2();
    }

    /**
     * Create an instance of {@link ReplySpiritV2 }
     * 
     */
    public ReplySpiritV2 createReplySpiritV2() {
        return new ReplySpiritV2();
    }

    /**
     * Create an instance of {@link ReplySSPV2 }
     * 
     */
    public ReplySSPV2 createReplySSPV2() {
        return new ReplySSPV2();
    }

    /**
     * Create an instance of {@link ReplyHistFormB }
     * 
     */
    public ReplyHistFormB createReplyHistFormB() {
        return new ReplyHistFormB();
    }

    /**
     * Create an instance of {@link ReplyRests }
     * 
     */
    public ReplyRests createReplyRests() {
        return new ReplyRests();
    }

    /**
     * Create an instance of {@link ReplyAP }
     * 
     */
    public ReplyAP createReplyAP() {
        return new ReplyAP();
    }

    /**
     * Create an instance of {@link ReplyClient }
     * 
     */
    public ReplyClient createReplyClient() {
        return new ReplyClient();
    }

    /**
     * Create an instance of {@link ReplySpirit }
     * 
     */
    public ReplySpirit createReplySpirit() {
        return new ReplySpirit();
    }

    /**
     * Create an instance of {@link ReplySSP }
     * 
     */
    public ReplySSP createReplySSP() {
        return new ReplySSP();
    }

    /**
     * Create an instance of {@link RepImportedType }
     * 
     */
    public RepImportedType createRepImportedType() {
        return new RepImportedType();
    }

    /**
     * Create an instance of {@link MarkInfoType2 }
     * 
     */
    public MarkInfoType2 createMarkInfoType2() {
        return new MarkInfoType2();
    }

    /**
     * Create an instance of {@link MarkInfoType2 .Ranges }
     * 
     */
    public MarkInfoType2 .Ranges createMarkInfoType2Ranges() {
        return new MarkInfoType2 .Ranges();
    }

    /**
     * Create an instance of {@link OrgInfoExV2 }
     * 
     */
    public OrgInfoExV2 createOrgInfoExV2() {
        return new OrgInfoExV2();
    }

    /**
     * Create an instance of {@link RepProducedType }
     * 
     */
    public RepProducedType createRepProducedType() {
        return new RepProducedType();
    }

    /**
     * Create an instance of {@link ActWriteOffType }
     * 
     */
    public ActWriteOffType createActWriteOffType() {
        return new ActWriteOffType();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType }
     * 
     */
    public WayBillInformBRegType createWayBillInformBRegType() {
        return new WayBillInformBRegType();
    }

    /**
     * Create an instance of {@link QueryParameters }
     * 
     */
    public QueryParameters createQueryParameters() {
        return new QueryParameters();
    }

    /**
     * Create an instance of {@link InformInvPositionType }
     * 
     */
    public InformInvPositionType createInformInvPositionType() {
        return new InformInvPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg }
     * 
     */
    public ActInventoryInformBReg createActInventoryInformBReg() {
        return new ActInventoryInformBReg();
    }

    /**
     * Create an instance of {@link ActChargeOnType }
     * 
     */
    public ActChargeOnType createActChargeOnType() {
        return new ActChargeOnType();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType }
     * 
     */
    public ActChargeOnPositionType createActChargeOnPositionType() {
        return new ActChargeOnPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryPositionType }
     * 
     */
    public ActInventoryPositionType createActInventoryPositionType() {
        return new ActInventoryPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryType }
     * 
     */
    public ActInventoryType createActInventoryType() {
        return new ActInventoryType();
    }

    /**
     * Create an instance of {@link ConfirmTicketType }
     * 
     */
    public ConfirmTicketType createConfirmTicketType() {
        return new ConfirmTicketType();
    }

    /**
     * Create an instance of {@link WayBillActType }
     * 
     */
    public WayBillActType createWayBillActType() {
        return new WayBillActType();
    }

    /**
     * Create an instance of {@link WayBillType }
     * 
     */
    public WayBillType createWayBillType() {
        return new WayBillType();
    }

    /**
     * Create an instance of {@link MarkInfoType }
     * 
     */
    public MarkInfoType createMarkInfoType() {
        return new MarkInfoType();
    }

    /**
     * Create an instance of {@link MarkInfoType.Ranges }
     * 
     */
    public MarkInfoType.Ranges createMarkInfoTypeRanges() {
        return new MarkInfoType.Ranges();
    }

    /**
     * Create an instance of {@link OrgInfoEx }
     * 
     */
    public OrgInfoEx createOrgInfoEx() {
        return new OrgInfoEx();
    }

    /**
     * Create an instance of {@link Documents }
     * 
     */
    public Documents createDocuments() {
        return new Documents();
    }

    /**
     * Create an instance of {@link SenderInfo }
     * 
     */
    public SenderInfo createSenderInfo() {
        return new SenderInfo();
    }

    /**
     * Create an instance of {@link DocBody }
     * 
     */
    public DocBody createDocBody() {
        return new DocBody();
    }

    /**
     * Create an instance of {@link MarkCodeInfoType }
     * 
     */
    public MarkCodeInfoType createMarkCodeInfoType() {
        return new MarkCodeInfoType();
    }

    /**
     * Create an instance of {@link OrgLicenseType }
     * 
     */
    public OrgLicenseType createOrgLicenseType() {
        return new OrgLicenseType();
    }

    /**
     * Create an instance of {@link OrgInfo }
     * 
     */
    public OrgInfo createOrgInfo() {
        return new OrgInfo();
    }

    /**
     * Create an instance of {@link ProductContractType }
     * 
     */
    public ProductContractType createProductContractType() {
        return new ProductContractType();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     * 
     */
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link OrgItemType }
     * 
     */
    public OrgItemType createOrgItemType() {
        return new OrgItemType();
    }

    /**
     * Create an instance of {@link OrgAddressType }
     * 
     */
    public OrgAddressType createOrgAddressType() {
        return new OrgAddressType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link InformBTypeItem }
     * 
     */
    public InformBTypeItem createInformBTypeItem() {
        return new InformBTypeItem();
    }

    /**
     * Create an instance of {@link InformAType }
     * 
     */
    public InformAType createInformAType() {
        return new InformAType();
    }

    /**
     * Create an instance of {@link InformBType }
     * 
     */
    public InformBType createInformBType() {
        return new InformBType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link TicketResultType }
     * 
     */
    public TicketResultType createTicketResultType() {
        return new TicketResultType();
    }

    /**
     * Create an instance of {@link OperationResultType }
     * 
     */
    public OperationResultType createOperationResultType() {
        return new OperationResultType();
    }

    /**
     * Create an instance of {@link TicketType }
     * 
     */
    public TicketType createTicketType() {
        return new TicketType();
    }

    /**
     * Create an instance of {@link PositionType2 }
     * 
     */
    public PositionType2 createPositionType2() {
        return new PositionType2();
    }

    /**
     * Create an instance of {@link InformBTypeRegItem }
     * 
     */
    public InformBTypeRegItem createInformBTypeRegItem() {
        return new InformBTypeRegItem();
    }

    /**
     * Create an instance of {@link InformARegType }
     * 
     */
    public InformARegType createInformARegType() {
        return new InformARegType();
    }

    /**
     * Create an instance of {@link MarkCodeInfoType2 }
     * 
     */
    public MarkCodeInfoType2 createMarkCodeInfoType2() {
        return new MarkCodeInfoType2();
    }

    /**
     * Create an instance of {@link InformABRegType }
     * 
     */
    public InformABRegType createInformABRegType() {
        return new InformABRegType();
    }

    /**
     * Create an instance of {@link InformABKeyType }
     * 
     */
    public InformABKeyType createInformABKeyType() {
        return new InformABKeyType();
    }

    /**
     * Create an instance of {@link InformInvBRegItem }
     * 
     */
    public InformInvBRegItem createInformInvBRegItem() {
        return new InformInvBRegItem();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link QueryFormAB }
     * 
     */
    public QueryFormAB createQueryFormAB() {
        return new QueryFormAB();
    }

    /**
     * Create an instance of {@link InformBPositionType }
     * 
     */
    public InformBPositionType createInformBPositionType() {
        return new InformBPositionType();
    }

    /**
     * Create an instance of {@link ActWriteOffPositionType }
     * 
     */
    public ActWriteOffPositionType createActWriteOffPositionType() {
        return new ActWriteOffPositionType();
    }

    /**
     * Create an instance of {@link PositionType3 }
     * 
     */
    public PositionType3 createPositionType3() {
        return new PositionType3();
    }

    /**
     * Create an instance of {@link UsedResourceType }
     * 
     */
    public UsedResourceType createUsedResourceType() {
        return new UsedResourceType();
    }

    /**
     * Create an instance of {@link OrgAddressTypeFOTS }
     * 
     */
    public OrgAddressTypeFOTS createOrgAddressTypeFOTS() {
        return new OrgAddressTypeFOTS();
    }

    /**
     * Create an instance of {@link TSType }
     * 
     */
    public TSType createTSType() {
        return new TSType();
    }

    /**
     * Create an instance of {@link OrgItemType2 }
     * 
     */
    public OrgItemType2 createOrgItemType2() {
        return new OrgItemType2();
    }

    /**
     * Create an instance of {@link ULType }
     * 
     */
    public ULType createULType() {
        return new ULType();
    }

    /**
     * Create an instance of {@link OrganizationsType2 }
     * 
     */
    public OrganizationsType2 createOrganizationsType2() {
        return new OrganizationsType2();
    }

    /**
     * Create an instance of {@link FOType }
     * 
     */
    public FOType createFOType() {
        return new FOType();
    }

    /**
     * Create an instance of {@link OrgInfoV2 }
     * 
     */
    public OrgInfoV2 createOrgInfoV2() {
        return new OrgInfoV2();
    }

    /**
     * Create an instance of {@link ProductContractType2 }
     * 
     */
    public ProductContractType2 createProductContractType2() {
        return new ProductContractType2();
    }

    /**
     * Create an instance of {@link FLType }
     * 
     */
    public FLType createFLType() {
        return new FLType();
    }

    /**
     * Create an instance of {@link OrgInfoRusReplyV2 }
     * 
     */
    public OrgInfoRusReplyV2 createOrgInfoRusReplyV2() {
        return new OrgInfoRusReplyV2();
    }

    /**
     * Create an instance of {@link OrgInfoReplyV2 }
     * 
     */
    public OrgInfoReplyV2 createOrgInfoReplyV2() {
        return new OrgInfoReplyV2();
    }

    /**
     * Create an instance of {@link FLReplyType }
     * 
     */
    public FLReplyType createFLReplyType() {
        return new FLReplyType();
    }

    /**
     * Create an instance of {@link OrgAddressTypeULFLReply }
     * 
     */
    public OrgAddressTypeULFLReply createOrgAddressTypeULFLReply() {
        return new OrgAddressTypeULFLReply();
    }

    /**
     * Create an instance of {@link OrgInfoForeignV2 }
     * 
     */
    public OrgInfoForeignV2 createOrgInfoForeignV2() {
        return new OrgInfoForeignV2();
    }

    /**
     * Create an instance of {@link TSReplyType }
     * 
     */
    public TSReplyType createTSReplyType() {
        return new TSReplyType();
    }

    /**
     * Create an instance of {@link ULReplyType }
     * 
     */
    public ULReplyType createULReplyType() {
        return new ULReplyType();
    }

    /**
     * Create an instance of {@link OrgInfoForeignReplyV2 }
     * 
     */
    public OrgInfoForeignReplyV2 createOrgInfoForeignReplyV2() {
        return new OrgInfoForeignReplyV2();
    }

    /**
     * Create an instance of {@link OrgAddressTypeULFL }
     * 
     */
    public OrgAddressTypeULFL createOrgAddressTypeULFL() {
        return new OrgAddressTypeULFL();
    }

    /**
     * Create an instance of {@link OrgInfoRusV2 }
     * 
     */
    public OrgInfoRusV2 createOrgInfoRusV2() {
        return new OrgInfoRusV2();
    }

    /**
     * Create an instance of {@link OrgAddressType2 }
     * 
     */
    public OrgAddressType2 createOrgAddressType2() {
        return new OrgAddressType2();
    }

    /**
     * Create an instance of {@link InformF2TypeItem }
     * 
     */
    public InformF2TypeItem createInformF2TypeItem() {
        return new InformF2TypeItem();
    }

    /**
     * Create an instance of {@link ProductsTypeV2 }
     * 
     */
    public ProductsTypeV2 createProductsTypeV2() {
        return new ProductsTypeV2();
    }

    /**
     * Create an instance of {@link InformF2Type }
     * 
     */
    public InformF2Type createInformF2Type() {
        return new InformF2Type();
    }

    /**
     * Create an instance of {@link ProductInfoReplyV2 }
     * 
     */
    public ProductInfoReplyV2 createProductInfoReplyV2() {
        return new ProductInfoReplyV2();
    }

    /**
     * Create an instance of {@link ProductInfoForeignV2 }
     * 
     */
    public ProductInfoForeignV2 createProductInfoForeignV2() {
        return new ProductInfoForeignV2();
    }

    /**
     * Create an instance of {@link ProductInfoRusV2 }
     * 
     */
    public ProductInfoRusV2 createProductInfoRusV2() {
        return new ProductInfoRusV2();
    }

    /**
     * Create an instance of {@link ProductInfoAsiiuV2 }
     * 
     */
    public ProductInfoAsiiuV2 createProductInfoAsiiuV2() {
        return new ProductInfoAsiiuV2();
    }

    /**
     * Create an instance of {@link InformF1Type }
     * 
     */
    public InformF1Type createInformF1Type() {
        return new InformF1Type();
    }

    /**
     * Create an instance of {@link ProductInfoTestV2 }
     * 
     */
    public ProductInfoTestV2 createProductInfoTestV2() {
        return new ProductInfoTestV2();
    }

    /**
     * Create an instance of {@link ProductInfoV2 }
     * 
     */
    public ProductInfoV2 createProductInfoV2() {
        return new ProductInfoV2();
    }

    /**
     * Create an instance of {@link PositionType4 }
     * 
     */
    public PositionType4 createPositionType4() {
        return new PositionType4();
    }

    /**
     * Create an instance of {@link StockPositionType }
     * 
     */
    public StockPositionType createStockPositionType() {
        return new StockPositionType();
    }

    /**
     * Create an instance of {@link ReplyFormA }
     * 
     */
    public ReplyFormA createReplyFormA() {
        return new ReplyFormA();
    }

    /**
     * Create an instance of {@link ReplyFormB }
     * 
     */
    public ReplyFormB createReplyFormB() {
        return new ReplyFormB();
    }

    /**
     * Create an instance of {@link OperationBType }
     * 
     */
    public OperationBType createOperationBType() {
        return new OperationBType();
    }

    /**
     * Create an instance of {@link ReplyClientVersion }
     * 
     */
    public ReplyClientVersion createReplyClientVersion() {
        return new ReplyClientVersion();
    }

    /**
     * Create an instance of {@link QueryRejectRepProduced }
     * 
     */
    public QueryRejectRepProduced createQueryRejectRepProduced() {
        return new QueryRejectRepProduced();
    }

    /**
     * Create an instance of {@link QueryRejectRepImported }
     * 
     */
    public QueryRejectRepImported createQueryRejectRepImported() {
        return new QueryRejectRepImported();
    }

    /**
     * Create an instance of {@link StockPositionType2 }
     * 
     */
    public StockPositionType2 createStockPositionType2() {
        return new StockPositionType2();
    }

    /**
     * Create an instance of {@link ReplyForm1 }
     * 
     */
    public ReplyForm1 createReplyForm1() {
        return new ReplyForm1();
    }

    /**
     * Create an instance of {@link ReplyForm2 }
     * 
     */
    public ReplyForm2 createReplyForm2() {
        return new ReplyForm2();
    }

    /**
     * Create an instance of {@link OperationBType2 }
     * 
     */
    public OperationBType2 createOperationBType2() {
        return new OperationBType2();
    }

    /**
     * Create an instance of {@link PositionType5 }
     * 
     */
    public PositionType5 createPositionType5() {
        return new PositionType5();
    }

    /**
     * Create an instance of {@link TransportType2 }
     * 
     */
    public TransportType2 createTransportType2() {
        return new TransportType2();
    }

    /**
     * Create an instance of {@link PositionType6 }
     * 
     */
    public PositionType6 createPositionType6() {
        return new PositionType6();
    }

    /**
     * Create an instance of {@link InformF1F2RegType }
     * 
     */
    public InformF1F2RegType createInformF1F2RegType() {
        return new InformF1F2RegType();
    }

    /**
     * Create an instance of {@link InformF2TypeRegItem }
     * 
     */
    public InformF2TypeRegItem createInformF2TypeRegItem() {
        return new InformF2TypeRegItem();
    }

    /**
     * Create an instance of {@link InformF1RegType }
     * 
     */
    public InformF1RegType createInformF1RegType() {
        return new InformF1RegType();
    }

    /**
     * Create an instance of {@link InformInvF2RegItem }
     * 
     */
    public InformInvF2RegItem createInformInvF2RegItem() {
        return new InformInvF2RegItem();
    }

    /**
     * Create an instance of {@link QueryFormF1F2 }
     * 
     */
    public QueryFormF1F2 createQueryFormF1F2() {
        return new QueryFormF1F2();
    }

    /**
     * Create an instance of {@link InformF2PositionType }
     * 
     */
    public InformF2PositionType createInformF2PositionType() {
        return new InformF2PositionType();
    }

    /**
     * Create an instance of {@link ActWriteOffPositionType2 }
     * 
     */
    public ActWriteOffPositionType2 createActWriteOffPositionType2() {
        return new ActWriteOffPositionType2();
    }

    /**
     * Create an instance of {@link ru.crystals.pos.egais.documents.InformF1F2 }
     * 
     */
    public ru.crystals.pos.egais.documents.InformF1F2 createInformF1F2() {
        return new ru.crystals.pos.egais.documents.InformF1F2();
    }

    /**
     * Create an instance of {@link TransferFromShopPositionType }
     * 
     */
    public TransferFromShopPositionType createTransferFromShopPositionType() {
        return new TransferFromShopPositionType();
    }

    /**
     * Create an instance of {@link TransferToShopPositionType }
     * 
     */
    public TransferToShopPositionType createTransferToShopPositionType() {
        return new TransferToShopPositionType();
    }

    /**
     * Create an instance of {@link InformF1PositionType }
     * 
     */
    public InformF1PositionType createInformF1PositionType() {
        return new InformF1PositionType();
    }

    /**
     * Create an instance of {@link NoAnswerType }
     * 
     */
    public NoAnswerType createNoAnswerType() {
        return new NoAnswerType();
    }

    /**
     * Create an instance of {@link ShopPositionType }
     * 
     */
    public ShopPositionType createShopPositionType() {
        return new ShopPositionType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link DataType2 }
     * 
     */
    public DataType2 createDataType2() {
        return new DataType2();
    }

    /**
     * Create an instance of {@link ActChargeOnShopPositionType }
     * 
     */
    public ActChargeOnShopPositionType createActChargeOnShopPositionType() {
        return new ActChargeOnShopPositionType();
    }

    /**
     * Create an instance of {@link ActWriteOffShopPositionType }
     * 
     */
    public ActWriteOffShopPositionType createActWriteOffShopPositionType() {
        return new ActWriteOffShopPositionType();
    }

    /**
     * Create an instance of {@link InfoVersionTTN }
     * 
     */
    public InfoVersionTTN createInfoVersionTTN() {
        return new InfoVersionTTN();
    }

    /**
     * Create an instance of {@link MarkType }
     * 
     */
    public MarkType createMarkType() {
        return new MarkType();
    }

    /**
     * Create an instance of {@link BarcodeType }
     * 
     */
    public BarcodeType createBarcodeType() {
        return new BarcodeType();
    }

    /**
     * Create an instance of {@link RequestRepealWB }
     * 
     */
    public RequestRepealWB createRequestRepealWB() {
        return new RequestRepealWB();
    }

    /**
     * Create an instance of {@link RequestRepealACO }
     * 
     */
    public RequestRepealACO createRequestRepealACO() {
        return new RequestRepealACO();
    }

    /**
     * Create an instance of {@link RequestRepealAWO }
     * 
     */
    public RequestRepealAWO createRequestRepealAWO() {
        return new RequestRepealAWO();
    }

    /**
     * Create an instance of {@link ConfirmRepealWB.Header }
     * 
     */
    public ConfirmRepealWB.Header createConfirmRepealWBHeader() {
        return new ConfirmRepealWB.Header();
    }

    /**
     * Create an instance of {@link ReplyBarcode.Marks }
     * 
     */
    public ReplyBarcode.Marks createReplyBarcodeMarks() {
        return new ReplyBarcode.Marks();
    }

    /**
     * Create an instance of {@link QueryBarcode.Marks }
     * 
     */
    public QueryBarcode.Marks createQueryBarcodeMarks() {
        return new QueryBarcode.Marks();
    }

    /**
     * Create an instance of {@link ActWriteOffShopTypeV2 .Header }
     * 
     */
    public ActWriteOffShopTypeV2 .Header createActWriteOffShopTypeV2Header() {
        return new ActWriteOffShopTypeV2 .Header();
    }

    /**
     * Create an instance of {@link ActWriteOffShopTypeV2 .Content }
     * 
     */
    public ActWriteOffShopTypeV2 .Content createActWriteOffShopTypeV2Content() {
        return new ActWriteOffShopTypeV2 .Content();
    }

    /**
     * Create an instance of {@link ActChargeOnShopTypeV2 .Header }
     * 
     */
    public ActChargeOnShopTypeV2 .Header createActChargeOnShopTypeV2Header() {
        return new ActChargeOnShopTypeV2 .Header();
    }

    /**
     * Create an instance of {@link ActChargeOnShopTypeV2 .Content }
     * 
     */
    public ActChargeOnShopTypeV2 .Content createActChargeOnShopTypeV2Content() {
        return new ActChargeOnShopTypeV2 .Content();
    }

    /**
     * Create an instance of {@link AsiiuTime.Sensor }
     * 
     */
    public AsiiuTime.Sensor createAsiiuTimeSensor() {
        return new AsiiuTime.Sensor();
    }

    /**
     * Create an instance of {@link AsiiuTime.Data }
     * 
     */
    public AsiiuTime.Data createAsiiuTimeData() {
        return new AsiiuTime.Data();
    }

    /**
     * Create an instance of {@link Asiiu.Sensor }
     * 
     */
    public Asiiu.Sensor createAsiiuSensor() {
        return new Asiiu.Sensor();
    }

    /**
     * Create an instance of {@link Asiiu.Data }
     * 
     */
    public Asiiu.Data createAsiiuData() {
        return new Asiiu.Data();
    }

    /**
     * Create an instance of {@link ReplyRestsShopV2 .Products }
     * 
     */
    public ReplyRestsShopV2 .Products createReplyRestsShopV2Products() {
        return new ReplyRestsShopV2 .Products();
    }

    /**
     * Create an instance of {@link NoAnswerTTN.Ttnlist }
     * 
     */
    public NoAnswerTTN.Ttnlist createNoAnswerTTNTtnlist() {
        return new NoAnswerTTN.Ttnlist();
    }

    /**
     * Create an instance of {@link RepPIInformF1RegType.Header }
     * 
     */
    public RepPIInformF1RegType.Header createRepPIInformF1RegTypeHeader() {
        return new RepPIInformF1RegType.Header();
    }

    /**
     * Create an instance of {@link RepPIInformF1RegType.Content }
     * 
     */
    public RepPIInformF1RegType.Content createRepPIInformF1RegTypeContent() {
        return new RepPIInformF1RegType.Content();
    }

    /**
     * Create an instance of {@link TransferToShopType.Header }
     * 
     */
    public TransferToShopType.Header createTransferToShopTypeHeader() {
        return new TransferToShopType.Header();
    }

    /**
     * Create an instance of {@link TransferToShopType.Content }
     * 
     */
    public TransferToShopType.Content createTransferToShopTypeContent() {
        return new TransferToShopType.Content();
    }

    /**
     * Create an instance of {@link TransferFromShopType.Header }
     * 
     */
    public TransferFromShopType.Header createTransferFromShopTypeHeader() {
        return new TransferFromShopType.Header();
    }

    /**
     * Create an instance of {@link TransferFromShopType.Content }
     * 
     */
    public TransferFromShopType.Content createTransferFromShopTypeContent() {
        return new TransferFromShopType.Content();
    }

    /**
     * Create an instance of {@link ActWriteOffTypeV2 .Header }
     * 
     */
    public ActWriteOffTypeV2 .Header createActWriteOffTypeV2Header() {
        return new ActWriteOffTypeV2 .Header();
    }

    /**
     * Create an instance of {@link ActWriteOffTypeV2 .Content }
     * 
     */
    public ActWriteOffTypeV2 .Content createActWriteOffTypeV2Content() {
        return new ActWriteOffTypeV2 .Content();
    }

    /**
     * Create an instance of {@link WayBillInformF2RegType.Header }
     * 
     */
    public WayBillInformF2RegType.Header createWayBillInformF2RegTypeHeader() {
        return new WayBillInformF2RegType.Header();
    }

    /**
     * Create an instance of {@link WayBillInformF2RegType.Content }
     * 
     */
    public WayBillInformF2RegType.Content createWayBillInformF2RegTypeContent() {
        return new WayBillInformF2RegType.Content();
    }

    /**
     * Create an instance of {@link InformInvPositionType2 .InformF2 }
     * 
     */
    public InformInvPositionType2 .InformF2 createInformInvPositionType2InformF2() {
        return new InformInvPositionType2 .InformF2();
    }

    /**
     * Create an instance of {@link ActInventoryInformF2Reg.Header }
     * 
     */
    public ActInventoryInformF2Reg.Header createActInventoryInformF2RegHeader() {
        return new ActInventoryInformF2Reg.Header();
    }

    /**
     * Create an instance of {@link ActInventoryInformF2Reg.Content }
     * 
     */
    public ActInventoryInformF2Reg.Content createActInventoryInformF2RegContent() {
        return new ActInventoryInformF2Reg.Content();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType2 .InformF1F2 }
     * 
     */
    public ActChargeOnPositionType2 .InformF1F2 createActChargeOnPositionType2InformF1F2() {
        return new ActChargeOnPositionType2 .InformF1F2();
    }

    /**
     * Create an instance of {@link ActChargeOnTypeV2 .Header }
     * 
     */
    public ActChargeOnTypeV2 .Header createActChargeOnTypeV2Header() {
        return new ActChargeOnTypeV2 .Header();
    }

    /**
     * Create an instance of {@link ActChargeOnTypeV2 .Content }
     * 
     */
    public ActChargeOnTypeV2 .Content createActChargeOnTypeV2Content() {
        return new ActChargeOnTypeV2 .Content();
    }

    /**
     * Create an instance of {@link WayBillActTypeV2 .Header }
     * 
     */
    public WayBillActTypeV2 .Header createWayBillActTypeV2Header() {
        return new WayBillActTypeV2 .Header();
    }

    /**
     * Create an instance of {@link WayBillActTypeV2 .Content }
     * 
     */
    public WayBillActTypeV2 .Content createWayBillActTypeV2Content() {
        return new WayBillActTypeV2 .Content();
    }

    /**
     * Create an instance of {@link WayBillTypeV2 .Header }
     * 
     */
    public WayBillTypeV2 .Header createWayBillTypeV2Header() {
        return new WayBillTypeV2 .Header();
    }

    /**
     * Create an instance of {@link WayBillTypeV2 .Content }
     * 
     */
    public WayBillTypeV2 .Content createWayBillTypeV2Content() {
        return new WayBillTypeV2 .Content();
    }

    /**
     * Create an instance of {@link ReplyHistForm2 .HistoryF2 }
     * 
     */
    public ReplyHistForm2 .HistoryF2 createReplyHistForm2HistoryF2() {
        return new ReplyHistForm2 .HistoryF2();
    }

    /**
     * Create an instance of {@link ReplyRestsV2 .Products }
     * 
     */
    public ReplyRestsV2 .Products createReplyRestsV2Products() {
        return new ReplyRestsV2 .Products();
    }

    /**
     * Create an instance of {@link ReplyAPV2 .Products }
     * 
     */
    public ReplyAPV2 .Products createReplyAPV2Products() {
        return new ReplyAPV2 .Products();
    }

    /**
     * Create an instance of {@link ReplyClientV2 .Clients }
     * 
     */
    public ReplyClientV2 .Clients createReplyClientV2Clients() {
        return new ReplyClientV2 .Clients();
    }

    /**
     * Create an instance of {@link ReplySpiritV2 .Products }
     * 
     */
    public ReplySpiritV2 .Products createReplySpiritV2Products() {
        return new ReplySpiritV2 .Products();
    }

    /**
     * Create an instance of {@link ReplySSPV2 .Products }
     * 
     */
    public ReplySSPV2 .Products createReplySSPV2Products() {
        return new ReplySSPV2 .Products();
    }

    /**
     * Create an instance of {@link ReplyHistFormB.HistoryB }
     * 
     */
    public ReplyHistFormB.HistoryB createReplyHistFormBHistoryB() {
        return new ReplyHistFormB.HistoryB();
    }

    /**
     * Create an instance of {@link ReplyRests.Products }
     * 
     */
    public ReplyRests.Products createReplyRestsProducts() {
        return new ReplyRests.Products();
    }

    /**
     * Create an instance of {@link ReplyAP.Products }
     * 
     */
    public ReplyAP.Products createReplyAPProducts() {
        return new ReplyAP.Products();
    }

    /**
     * Create an instance of {@link ReplyClient.Clients }
     * 
     */
    public ReplyClient.Clients createReplyClientClients() {
        return new ReplyClient.Clients();
    }

    /**
     * Create an instance of {@link ReplySpirit.Products }
     * 
     */
    public ReplySpirit.Products createReplySpiritProducts() {
        return new ReplySpirit.Products();
    }

    /**
     * Create an instance of {@link ReplySSP.Products }
     * 
     */
    public ReplySSP.Products createReplySSPProducts() {
        return new ReplySSP.Products();
    }

    /**
     * Create an instance of {@link RepImportedType.Header }
     * 
     */
    public RepImportedType.Header createRepImportedTypeHeader() {
        return new RepImportedType.Header();
    }

    /**
     * Create an instance of {@link RepImportedType.Content }
     * 
     */
    public RepImportedType.Content createRepImportedTypeContent() {
        return new RepImportedType.Content();
    }

    /**
     * Create an instance of {@link MarkInfoType2 .Ranges.Range }
     * 
     */
    public MarkInfoType2 .Ranges.Range createMarkInfoType2RangesRange() {
        return new MarkInfoType2 .Ranges.Range();
    }

    /**
     * Create an instance of {@link OrgInfoExV2 .Addresslist }
     * 
     */
    public OrgInfoExV2 .Addresslist createOrgInfoExV2Addresslist() {
        return new OrgInfoExV2 .Addresslist();
    }

    /**
     * Create an instance of {@link RepProducedType.Header }
     * 
     */
    public RepProducedType.Header createRepProducedTypeHeader() {
        return new RepProducedType.Header();
    }

    /**
     * Create an instance of {@link RepProducedType.Content }
     * 
     */
    public RepProducedType.Content createRepProducedTypeContent() {
        return new RepProducedType.Content();
    }

    /**
     * Create an instance of {@link RepProducedType.ContentResource }
     * 
     */
    public RepProducedType.ContentResource createRepProducedTypeContentResource() {
        return new RepProducedType.ContentResource();
    }

    /**
     * Create an instance of {@link ActWriteOffType.Header }
     * 
     */
    public ActWriteOffType.Header createActWriteOffTypeHeader() {
        return new ActWriteOffType.Header();
    }

    /**
     * Create an instance of {@link ActWriteOffType.Content }
     * 
     */
    public ActWriteOffType.Content createActWriteOffTypeContent() {
        return new ActWriteOffType.Content();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType.Header }
     * 
     */
    public WayBillInformBRegType.Header createWayBillInformBRegTypeHeader() {
        return new WayBillInformBRegType.Header();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType.Content }
     * 
     */
    public WayBillInformBRegType.Content createWayBillInformBRegTypeContent() {
        return new WayBillInformBRegType.Content();
    }

    /**
     * Create an instance of {@link QueryParameters.Parameters }
     * 
     */
    public QueryParameters.Parameters createQueryParametersParameters() {
        return new QueryParameters.Parameters();
    }

    /**
     * Create an instance of {@link InformInvPositionType.InformB }
     * 
     */
    public InformInvPositionType.InformB createInformInvPositionTypeInformB() {
        return new InformInvPositionType.InformB();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg.Header }
     * 
     */
    public ActInventoryInformBReg.Header createActInventoryInformBRegHeader() {
        return new ActInventoryInformBReg.Header();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg.Content }
     * 
     */
    public ActInventoryInformBReg.Content createActInventoryInformBRegContent() {
        return new ActInventoryInformBReg.Content();
    }

    /**
     * Create an instance of {@link ActChargeOnType.Header }
     * 
     */
    public ActChargeOnType.Header createActChargeOnTypeHeader() {
        return new ActChargeOnType.Header();
    }

    /**
     * Create an instance of {@link ActChargeOnType.Content }
     * 
     */
    public ActChargeOnType.Content createActChargeOnTypeContent() {
        return new ActChargeOnType.Content();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType.InformAB }
     * 
     */
    public ActChargeOnPositionType.InformAB createActChargeOnPositionTypeInformAB() {
        return new ActChargeOnPositionType.InformAB();
    }

    /**
     * Create an instance of {@link ActInventoryPositionType.InformB }
     * 
     */
    public ActInventoryPositionType.InformB createActInventoryPositionTypeInformB() {
        return new ActInventoryPositionType.InformB();
    }

    /**
     * Create an instance of {@link ActInventoryType.Header }
     * 
     */
    public ActInventoryType.Header createActInventoryTypeHeader() {
        return new ActInventoryType.Header();
    }

    /**
     * Create an instance of {@link ActInventoryType.Content }
     * 
     */
    public ActInventoryType.Content createActInventoryTypeContent() {
        return new ActInventoryType.Content();
    }

    /**
     * Create an instance of {@link ConfirmTicketType.Header }
     * 
     */
    public ConfirmTicketType.Header createConfirmTicketTypeHeader() {
        return new ConfirmTicketType.Header();
    }

    /**
     * Create an instance of {@link WayBillActType.Header }
     * 
     */
    public WayBillActType.Header createWayBillActTypeHeader() {
        return new WayBillActType.Header();
    }

    /**
     * Create an instance of {@link WayBillActType.Content }
     * 
     */
    public WayBillActType.Content createWayBillActTypeContent() {
        return new WayBillActType.Content();
    }

    /**
     * Create an instance of {@link WayBillType.Header }
     * 
     */
    public WayBillType.Header createWayBillTypeHeader() {
        return new WayBillType.Header();
    }

    /**
     * Create an instance of {@link WayBillType.Content }
     * 
     */
    public WayBillType.Content createWayBillTypeContent() {
        return new WayBillType.Content();
    }

    /**
     * Create an instance of {@link MarkInfoType.Ranges.Range }
     * 
     */
    public MarkInfoType.Ranges.Range createMarkInfoTypeRangesRange() {
        return new MarkInfoType.Ranges.Range();
    }

    /**
     * Create an instance of {@link OrgInfoEx.Addresslist }
     * 
     */
    public OrgInfoEx.Addresslist createOrgInfoExAddresslist() {
        return new OrgInfoEx.Addresslist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoINN(String value) {
        return new JAXBElement<String>(_OrgInfoINN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoRNN(String value) {
        return new JAXBElement<String>(_OrgInfoRNN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoUNP(String value) {
        return new JAXBElement<String>(_OrgInfoUNP_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExINN(String value) {
        return new JAXBElement<String>(_OrgInfoINN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExRNN(String value) {
        return new JAXBElement<String>(_OrgInfoRNN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExUNP(String value) {
        return new JAXBElement<String>(_OrgInfoUNP_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "State", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExState(String value) {
        return new JAXBElement<String>(_OrgInfoExState_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "TSNUM", scope = TSReplyType.class)
    public JAXBElement<String> createTSReplyTypeTSNUM(String value) {
        return new JAXBElement<String>(_TSReplyTypeTSNUM_QNAME, String.class, TSReplyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "State", scope = OrgInfoExV2 .class)
    public JAXBElement<String> createOrgInfoExV2State(String value) {
        return new JAXBElement<String>(_OrgInfoExV2State_QNAME, String.class, OrgInfoExV2 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "VersionWB", scope = OrgInfoExV2 .class)
    public JAXBElement<String> createOrgInfoExV2VersionWB(String value) {
        return new JAXBElement<String>(_OrgInfoExV2VersionWB_QNAME, String.class, OrgInfoExV2 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "TSNUM", scope = TSType.class)
    public JAXBElement<String> createTSTypeTSNUM(String value) {
        return new JAXBElement<String>(_TSReplyTypeTSNUM_QNAME, String.class, TSType.class, value);
    }

}
