//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 12:53:14 PM MSK 
//

@XmlSchema(xmlns = { 

                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01", prefix = "ns"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/Common", prefix = "c"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/CommonEnum", prefix = "ce"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ClientRef", prefix = "oref"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ProductRef", prefix = "pref"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNSingle", prefix = "wb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/Ticket", prefix = "tc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActTTNSingle", prefix = "wa"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ConfirmTicket", prefix = "ctc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActInventorySingle", prefix = "ain"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActChargeOn", prefix = "ainp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryParameters", prefix = "qp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNInformBReg", prefix = "wbr"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActInventoryInformBReg", prefix = "aint"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryFormAB", prefix = "qf"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActWriteOff", prefix = "awr"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RepProducedProduct", prefix = "rpp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RepImportedProduct", prefix = "rpi"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySSP", prefix = "rssp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySpirit", prefix = "rs"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyClient", prefix = "rc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyAP", prefix = "rap"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyRests", prefix = "rst"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyFormA", prefix = "rfa"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyFormB", prefix = "rfb"),

                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyHistFormB", prefix = "rfhb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyClientVersion", prefix = "orefv"),

                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ClientRef_v2", prefix = "oref2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ProductRef_v2", prefix = "pref2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryRejectRepProduced", prefix = "qrrp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryRejectRepImported", prefix = "qrri"),

                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySSP_v2", prefix = "rssp2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySpirit_v2", prefix = "rs2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyClient_v2", prefix = "rc2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyAP_v2", prefix = "rap2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyRests_v2", prefix = "rst2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyForm1", prefix = "rfa2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyForm2", prefix = "rfb2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyHistForm2", prefix = "rfhb2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNSingle_v2", prefix = "wb2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActTTNSingle_v2", prefix = "wa2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActChargeOn_v2", prefix = "ainp2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNInformF2Reg", prefix = "wbr2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActInventoryInformF2Reg", prefix = "aint2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryFormF1F2", prefix = "qf2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActWriteOff_v2", prefix = "awr2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TransferFromShop", prefix = "tfs"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TransferToShop", prefix = "tts"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RepInformF1Reg", prefix = "ripf1"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyNoAnswerTTN", prefix = "nattn"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyRestsShop_v2", prefix = "rsts2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/Asiiu", prefix = "asiu"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/AsiiuTime", prefix = "asiut"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActChargeOnShop_v2", prefix = "ains2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActWriteOffShop_v2", prefix = "awrs2"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/InfoVersionTTN", prefix = "wbfu"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryBarcode", prefix = "qbc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyBarcode", prefix = "rbc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RequestRepealWB", prefix = "rrwb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ConfirmRepealWB", prefix = "crwb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RequestRepealACO", prefix = "rraco"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/RequestRepealAWO", prefix = "rrawo")
            }, 
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package ru.crystals.pos.egais.documents;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
