//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 11:00:14 AM MSK 
//


package ru.crystals.egais.documents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Owner" type="{http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01}SenderInfo"/>
 *         &lt;element name="Document">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="WayBill" type="{http://fsrar.ru/WEGAIS/TTNSingle}WayBillType" minOccurs="0"/>
 *                   &lt;element name="Ticket" type="{http://fsrar.ru/WEGAIS/Ticket}TicketType" minOccurs="0"/>
 *                   &lt;element name="WayBillAct" type="{http://fsrar.ru/WEGAIS/ActTTNSingle}WayBillActType" minOccurs="0"/>
 *                   &lt;element name="ConfirmTicket" type="{http://fsrar.ru/WEGAIS/ConfirmTicket}ConfirmTicketType" minOccurs="0"/>
 *                   &lt;element name="TTNInformBReg" type="{http://fsrar.ru/WEGAIS/TTNInformBReg}WayBillInformBRegType" minOccurs="0"/>
 *                   &lt;element name="ActInventory" type="{http://fsrar.ru/WEGAIS/ActInventorySingle}ActInventoryType" minOccurs="0"/>
 *                   &lt;element name="ActChargeOn" type="{http://fsrar.ru/WEGAIS/ActChargeOn}ActChargeOnType" minOccurs="0"/>
 *                   &lt;element name="ActInventoryInformBReg" type="{http://fsrar.ru/WEGAIS/ActInventoryInformBReg}ActInventoryInformBReg" minOccurs="0"/>
 *                   &lt;element name="QueryAP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
 *                   &lt;element name="QuerySSP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
 *                   &lt;element name="QuerySP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
 *                   &lt;element name="QueryClients" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
 *                   &lt;element name="QueryRests" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
 *                   &lt;element name="QueryFormA" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB" minOccurs="0"/>
 *                   &lt;element name="QueryFormB" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB" minOccurs="0"/>
 *                   &lt;element name="ReplySSP" type="{http://fsrar.ru/WEGAIS/ReplySSP}ReplySSP" minOccurs="0"/>
 *                   &lt;element name="ReplySpirit" type="{http://fsrar.ru/WEGAIS/ReplySpirit}ReplySpirit" minOccurs="0"/>
 *                   &lt;element name="ReplyClient" type="{http://fsrar.ru/WEGAIS/ReplyClient}ReplyClient" minOccurs="0"/>
 *                   &lt;element name="ReplyAP" type="{http://fsrar.ru/WEGAIS/ReplyAP}ReplyAP" minOccurs="0"/>
 *                   &lt;element name="ReplyRests" type="{http://fsrar.ru/WEGAIS/ReplyRests}ReplyRests" minOccurs="0"/>
 *                   &lt;element name="ReplyFormA" type="{http://fsrar.ru/WEGAIS/ReplyFormA}ReplyFormA" minOccurs="0"/>
 *                   &lt;element name="ReplyFormB" type="{http://fsrar.ru/WEGAIS/ReplyFormB}ReplyFormB" minOccurs="0"/>
 *                   &lt;element name="ActWriteOff" type="{http://fsrar.ru/WEGAIS/ActWriteOff}ActWriteOffType" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString" default="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "owner",
    "document"
})
@XmlRootElement(name = "Documents", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
public class Documents {

    @XmlElement(name = "Owner", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01", required = true)
    protected SenderInfo owner;
    @XmlElement(name = "Document", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01", required = true)
    protected Documents.Document document;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link SenderInfo }
     *     
     */
    public SenderInfo getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderInfo }
     *     
     */
    public void setOwner(SenderInfo value) {
        this.owner = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link Documents.Document }
     *     
     */
    public Documents.Document getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documents.Document }
     *     
     */
    public void setDocument(Documents.Document value) {
        this.document = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="WayBill" type="{http://fsrar.ru/WEGAIS/TTNSingle}WayBillType" minOccurs="0"/>
     *         &lt;element name="Ticket" type="{http://fsrar.ru/WEGAIS/Ticket}TicketType" minOccurs="0"/>
     *         &lt;element name="WayBillAct" type="{http://fsrar.ru/WEGAIS/ActTTNSingle}WayBillActType" minOccurs="0"/>
     *         &lt;element name="ConfirmTicket" type="{http://fsrar.ru/WEGAIS/ConfirmTicket}ConfirmTicketType" minOccurs="0"/>
     *         &lt;element name="TTNInformBReg" type="{http://fsrar.ru/WEGAIS/TTNInformBReg}WayBillInformBRegType" minOccurs="0"/>
     *         &lt;element name="ActInventory" type="{http://fsrar.ru/WEGAIS/ActInventorySingle}ActInventoryType" minOccurs="0"/>
     *         &lt;element name="ActChargeOn" type="{http://fsrar.ru/WEGAIS/ActChargeOn}ActChargeOnType" minOccurs="0"/>
     *         &lt;element name="ActInventoryInformBReg" type="{http://fsrar.ru/WEGAIS/ActInventoryInformBReg}ActInventoryInformBReg" minOccurs="0"/>
     *         &lt;element name="QueryAP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
     *         &lt;element name="QuerySSP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
     *         &lt;element name="QuerySP" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
     *         &lt;element name="QueryClients" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
     *         &lt;element name="QueryRests" type="{http://fsrar.ru/WEGAIS/QueryParameters}QueryParameters" minOccurs="0"/>
     *         &lt;element name="QueryFormA" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB" minOccurs="0"/>
     *         &lt;element name="QueryFormB" type="{http://fsrar.ru/WEGAIS/QueryFormAB}QueryFormAB" minOccurs="0"/>
     *         &lt;element name="ReplySSP" type="{http://fsrar.ru/WEGAIS/ReplySSP}ReplySSP" minOccurs="0"/>
     *         &lt;element name="ReplySpirit" type="{http://fsrar.ru/WEGAIS/ReplySpirit}ReplySpirit" minOccurs="0"/>
     *         &lt;element name="ReplyClient" type="{http://fsrar.ru/WEGAIS/ReplyClient}ReplyClient" minOccurs="0"/>
     *         &lt;element name="ReplyAP" type="{http://fsrar.ru/WEGAIS/ReplyAP}ReplyAP" minOccurs="0"/>
     *         &lt;element name="ReplyRests" type="{http://fsrar.ru/WEGAIS/ReplyRests}ReplyRests" minOccurs="0"/>
     *         &lt;element name="ReplyFormA" type="{http://fsrar.ru/WEGAIS/ReplyFormA}ReplyFormA" minOccurs="0"/>
     *         &lt;element name="ReplyFormB" type="{http://fsrar.ru/WEGAIS/ReplyFormB}ReplyFormB" minOccurs="0"/>
     *         &lt;element name="ActWriteOff" type="{http://fsrar.ru/WEGAIS/ActWriteOff}ActWriteOffType" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "wayBill",
        "ticket",
        "wayBillAct",
        "confirmTicket",
        "ttnInformBReg",
        "actInventory",
        "actChargeOn",
        "actInventoryInformBReg",
        "queryAP",
        "querySSP",
        "querySP",
        "queryClients",
        "queryRests",
        "queryFormA",
        "queryFormB",
        "replySSP",
        "replySpirit",
        "replyClient",
        "replyAP",
        "replyRests",
        "replyFormA",
        "replyFormB",
        "actWriteOff"
    })
    public static class Document {

        @XmlElement(name = "WayBill", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected WayBillType wayBill;
        @XmlElement(name = "Ticket", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected TicketType ticket;
        @XmlElement(name = "WayBillAct", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected WayBillActType wayBillAct;
        @XmlElement(name = "ConfirmTicket", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ConfirmTicketType confirmTicket;
        @XmlElement(name = "TTNInformBReg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected WayBillInformBRegType ttnInformBReg;
        @XmlElement(name = "ActInventory", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ActInventoryType actInventory;
        @XmlElement(name = "ActChargeOn", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ActChargeOnType actChargeOn;
        @XmlElement(name = "ActInventoryInformBReg", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ActInventoryInformBReg actInventoryInformBReg;
        @XmlElement(name = "QueryAP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryParameters queryAP;
        @XmlElement(name = "QuerySSP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryParameters querySSP;
        @XmlElement(name = "QuerySP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryParameters querySP;
        @XmlElement(name = "QueryClients", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryParameters queryClients;
        @XmlElement(name = "QueryRests", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryParameters queryRests;
        @XmlElement(name = "QueryFormA", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryFormAB queryFormA;
        @XmlElement(name = "QueryFormB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected QueryFormAB queryFormB;
        @XmlElement(name = "ReplySSP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplySSP replySSP;
        @XmlElement(name = "ReplySpirit", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplySpirit replySpirit;
        @XmlElement(name = "ReplyClient", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplyClient replyClient;
        @XmlElement(name = "ReplyAP", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplyAP replyAP;
        @XmlElement(name = "ReplyRests", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplyRests replyRests;
        @XmlElement(name = "ReplyFormA", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplyFormA replyFormA;
        @XmlElement(name = "ReplyFormB", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ReplyFormB replyFormB;
        @XmlElement(name = "ActWriteOff", namespace = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01")
        protected ActWriteOffType actWriteOff;

        /**
         * Gets the value of the wayBill property.
         * 
         * @return
         *     possible object is
         *     {@link WayBillType }
         *     
         */
        public WayBillType getWayBill() {
            return wayBill;
        }

        /**
         * Sets the value of the wayBill property.
         * 
         * @param value
         *     allowed object is
         *     {@link WayBillType }
         *     
         */
        public void setWayBill(WayBillType value) {
            this.wayBill = value;
        }

        /**
         * Gets the value of the ticket property.
         * 
         * @return
         *     possible object is
         *     {@link TicketType }
         *     
         */
        public TicketType getTicket() {
            return ticket;
        }

        /**
         * Sets the value of the ticket property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketType }
         *     
         */
        public void setTicket(TicketType value) {
            this.ticket = value;
        }

        /**
         * Gets the value of the wayBillAct property.
         * 
         * @return
         *     possible object is
         *     {@link WayBillActType }
         *     
         */
        public WayBillActType getWayBillAct() {
            return wayBillAct;
        }

        /**
         * Sets the value of the wayBillAct property.
         * 
         * @param value
         *     allowed object is
         *     {@link WayBillActType }
         *     
         */
        public void setWayBillAct(WayBillActType value) {
            this.wayBillAct = value;
        }

        /**
         * Gets the value of the confirmTicket property.
         * 
         * @return
         *     possible object is
         *     {@link ConfirmTicketType }
         *     
         */
        public ConfirmTicketType getConfirmTicket() {
            return confirmTicket;
        }

        /**
         * Sets the value of the confirmTicket property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConfirmTicketType }
         *     
         */
        public void setConfirmTicket(ConfirmTicketType value) {
            this.confirmTicket = value;
        }

        /**
         * Gets the value of the ttnInformBReg property.
         * 
         * @return
         *     possible object is
         *     {@link WayBillInformBRegType }
         *     
         */
        public WayBillInformBRegType getTTNInformBReg() {
            return ttnInformBReg;
        }

        /**
         * Sets the value of the ttnInformBReg property.
         * 
         * @param value
         *     allowed object is
         *     {@link WayBillInformBRegType }
         *     
         */
        public void setTTNInformBReg(WayBillInformBRegType value) {
            this.ttnInformBReg = value;
        }

        /**
         * Gets the value of the actInventory property.
         * 
         * @return
         *     possible object is
         *     {@link ActInventoryType }
         *     
         */
        public ActInventoryType getActInventory() {
            return actInventory;
        }

        /**
         * Sets the value of the actInventory property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActInventoryType }
         *     
         */
        public void setActInventory(ActInventoryType value) {
            this.actInventory = value;
        }

        /**
         * Gets the value of the actChargeOn property.
         * 
         * @return
         *     possible object is
         *     {@link ActChargeOnType }
         *     
         */
        public ActChargeOnType getActChargeOn() {
            return actChargeOn;
        }

        /**
         * Sets the value of the actChargeOn property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActChargeOnType }
         *     
         */
        public void setActChargeOn(ActChargeOnType value) {
            this.actChargeOn = value;
        }

        /**
         * Gets the value of the actInventoryInformBReg property.
         * 
         * @return
         *     possible object is
         *     {@link ActInventoryInformBReg }
         *     
         */
        public ActInventoryInformBReg getActInventoryInformBReg() {
            return actInventoryInformBReg;
        }

        /**
         * Sets the value of the actInventoryInformBReg property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActInventoryInformBReg }
         *     
         */
        public void setActInventoryInformBReg(ActInventoryInformBReg value) {
            this.actInventoryInformBReg = value;
        }

        /**
         * Gets the value of the queryAP property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters }
         *     
         */
        public QueryParameters getQueryAP() {
            return queryAP;
        }

        /**
         * Sets the value of the queryAP property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters }
         *     
         */
        public void setQueryAP(QueryParameters value) {
            this.queryAP = value;
        }

        /**
         * Gets the value of the querySSP property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters }
         *     
         */
        public QueryParameters getQuerySSP() {
            return querySSP;
        }

        /**
         * Sets the value of the querySSP property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters }
         *     
         */
        public void setQuerySSP(QueryParameters value) {
            this.querySSP = value;
        }

        /**
         * Gets the value of the querySP property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters }
         *     
         */
        public QueryParameters getQuerySP() {
            return querySP;
        }

        /**
         * Sets the value of the querySP property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters }
         *     
         */
        public void setQuerySP(QueryParameters value) {
            this.querySP = value;
        }

        /**
         * Gets the value of the queryClients property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters }
         *     
         */
        public QueryParameters getQueryClients() {
            return queryClients;
        }

        /**
         * Sets the value of the queryClients property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters }
         *     
         */
        public void setQueryClients(QueryParameters value) {
            this.queryClients = value;
        }

        /**
         * Gets the value of the queryRests property.
         * 
         * @return
         *     possible object is
         *     {@link QueryParameters }
         *     
         */
        public QueryParameters getQueryRests() {
            return queryRests;
        }

        /**
         * Sets the value of the queryRests property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryParameters }
         *     
         */
        public void setQueryRests(QueryParameters value) {
            this.queryRests = value;
        }

        /**
         * Gets the value of the queryFormA property.
         * 
         * @return
         *     possible object is
         *     {@link QueryFormAB }
         *     
         */
        public QueryFormAB getQueryFormA() {
            return queryFormA;
        }

        /**
         * Sets the value of the queryFormA property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryFormAB }
         *     
         */
        public void setQueryFormA(QueryFormAB value) {
            this.queryFormA = value;
        }

        /**
         * Gets the value of the queryFormB property.
         * 
         * @return
         *     possible object is
         *     {@link QueryFormAB }
         *     
         */
        public QueryFormAB getQueryFormB() {
            return queryFormB;
        }

        /**
         * Sets the value of the queryFormB property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryFormAB }
         *     
         */
        public void setQueryFormB(QueryFormAB value) {
            this.queryFormB = value;
        }

        /**
         * Gets the value of the replySSP property.
         * 
         * @return
         *     possible object is
         *     {@link ReplySSP }
         *     
         */
        public ReplySSP getReplySSP() {
            return replySSP;
        }

        /**
         * Sets the value of the replySSP property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplySSP }
         *     
         */
        public void setReplySSP(ReplySSP value) {
            this.replySSP = value;
        }

        /**
         * Gets the value of the replySpirit property.
         * 
         * @return
         *     possible object is
         *     {@link ReplySpirit }
         *     
         */
        public ReplySpirit getReplySpirit() {
            return replySpirit;
        }

        /**
         * Sets the value of the replySpirit property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplySpirit }
         *     
         */
        public void setReplySpirit(ReplySpirit value) {
            this.replySpirit = value;
        }

        /**
         * Gets the value of the replyClient property.
         * 
         * @return
         *     possible object is
         *     {@link ReplyClient }
         *     
         */
        public ReplyClient getReplyClient() {
            return replyClient;
        }

        /**
         * Sets the value of the replyClient property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplyClient }
         *     
         */
        public void setReplyClient(ReplyClient value) {
            this.replyClient = value;
        }

        /**
         * Gets the value of the replyAP property.
         * 
         * @return
         *     possible object is
         *     {@link ReplyAP }
         *     
         */
        public ReplyAP getReplyAP() {
            return replyAP;
        }

        /**
         * Sets the value of the replyAP property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplyAP }
         *     
         */
        public void setReplyAP(ReplyAP value) {
            this.replyAP = value;
        }

        /**
         * Gets the value of the replyRests property.
         * 
         * @return
         *     possible object is
         *     {@link ReplyRests }
         *     
         */
        public ReplyRests getReplyRests() {
            return replyRests;
        }

        /**
         * Sets the value of the replyRests property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplyRests }
         *     
         */
        public void setReplyRests(ReplyRests value) {
            this.replyRests = value;
        }

        /**
         * Gets the value of the replyFormA property.
         * 
         * @return
         *     possible object is
         *     {@link ReplyFormA }
         *     
         */
        public ReplyFormA getReplyFormA() {
            return replyFormA;
        }

        /**
         * Sets the value of the replyFormA property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplyFormA }
         *     
         */
        public void setReplyFormA(ReplyFormA value) {
            this.replyFormA = value;
        }

        /**
         * Gets the value of the replyFormB property.
         * 
         * @return
         *     possible object is
         *     {@link ReplyFormB }
         *     
         */
        public ReplyFormB getReplyFormB() {
            return replyFormB;
        }

        /**
         * Sets the value of the replyFormB property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReplyFormB }
         *     
         */
        public void setReplyFormB(ReplyFormB value) {
            this.replyFormB = value;
        }

        /**
         * Gets the value of the actWriteOff property.
         * 
         * @return
         *     possible object is
         *     {@link ActWriteOffType }
         *     
         */
        public ActWriteOffType getActWriteOff() {
            return actWriteOff;
        }

        /**
         * Sets the value of the actWriteOff property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActWriteOffType }
         *     
         */
        public void setActWriteOff(ActWriteOffType value) {
            this.actWriteOff = value;
        }

    }

}
