//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 11:40:39 AM MSK 
//

@XmlSchema(xmlns = { 
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01"      , prefix = "ns"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/Common"                , prefix = "c"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ClientRef"             , prefix = "oref"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ProductRef"            , prefix = "pref"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNSingle"             , prefix = "wb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/Ticket"                , prefix = "tc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActTTNSingle"          , prefix = "wa"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ConfirmTicket"         , prefix = "ctc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActInventorySingle"    , prefix = "ain"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActChargeOn"           , prefix = "ainp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryParameters"       , prefix = "qp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySSP"              , prefix = "rssp"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplySpirit"           , prefix = "rs"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyClient"           , prefix = "rc"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyAP"               , prefix = "rap"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyRests"            , prefix = "rst"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/TTNInformBReg"         , prefix = "wbr"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActInventoryInformBReg", prefix = "aint"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/QueryFormAB"           , prefix = "qf"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyFormA"            , prefix = "rfa"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ReplyFormB"            , prefix = "rfb"),
                @XmlNs(namespaceURI = "http://fsrar.ru/WEGAIS/ActWriteOff"           , prefix = "awr")
            }, 
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package ru.crystals.egais.documents;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
