//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 11:00:14 AM MSK 
//


package ru.crystals.egais.documents;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.crystals.pos.egais.documents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrgInfoExINN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "INN");
    private final static QName _OrgInfoExRNN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "RNN");
    private final static QName _OrgInfoExUNP_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "UNP");
    private final static QName _OrgInfoExState_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "State");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.crystals.pos.egais.documents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Documents }
     * 
     */
    public Documents createDocuments() {
        return new Documents();
    }

    /**
     * Create an instance of {@link ActWriteOffType }
     * 
     */
    public ActWriteOffType createActWriteOffType() {
        return new ActWriteOffType();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType }
     * 
     */
    public WayBillInformBRegType createWayBillInformBRegType() {
        return new WayBillInformBRegType();
    }

    /**
     * Create an instance of {@link ReplyRests }
     * 
     */
    public ReplyRests createReplyRests() {
        return new ReplyRests();
    }

    /**
     * Create an instance of {@link ReplyAP }
     * 
     */
    public ReplyAP createReplyAP() {
        return new ReplyAP();
    }

    /**
     * Create an instance of {@link ReplyClient }
     * 
     */
    public ReplyClient createReplyClient() {
        return new ReplyClient();
    }

    /**
     * Create an instance of {@link ReplySpirit }
     * 
     */
    public ReplySpirit createReplySpirit() {
        return new ReplySpirit();
    }

    /**
     * Create an instance of {@link ReplySSP }
     * 
     */
    public ReplySSP createReplySSP() {
        return new ReplySSP();
    }

    /**
     * Create an instance of {@link QueryParameters }
     * 
     */
    public QueryParameters createQueryParameters() {
        return new QueryParameters();
    }

    /**
     * Create an instance of {@link InformInvPositionType }
     * 
     */
    public InformInvPositionType createInformInvPositionType() {
        return new InformInvPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg }
     * 
     */
    public ActInventoryInformBReg createActInventoryInformBReg() {
        return new ActInventoryInformBReg();
    }

    /**
     * Create an instance of {@link ActChargeOnType }
     * 
     */
    public ActChargeOnType createActChargeOnType() {
        return new ActChargeOnType();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType }
     * 
     */
    public ActChargeOnPositionType createActChargeOnPositionType() {
        return new ActChargeOnPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryPositionType }
     * 
     */
    public ActInventoryPositionType createActInventoryPositionType() {
        return new ActInventoryPositionType();
    }

    /**
     * Create an instance of {@link ActInventoryType }
     * 
     */
    public ActInventoryType createActInventoryType() {
        return new ActInventoryType();
    }

    /**
     * Create an instance of {@link ConfirmTicketType }
     * 
     */
    public ConfirmTicketType createConfirmTicketType() {
        return new ConfirmTicketType();
    }

    /**
     * Create an instance of {@link WayBillActType }
     * 
     */
    public WayBillActType createWayBillActType() {
        return new WayBillActType();
    }

    /**
     * Create an instance of {@link WayBillType }
     * 
     */
    public WayBillType createWayBillType() {
        return new WayBillType();
    }

    /**
     * Create an instance of {@link MarkInfoType }
     * 
     */
    public MarkInfoType createMarkInfoType() {
        return new MarkInfoType();
    }

    /**
     * Create an instance of {@link MarkInfoType.Ranges }
     * 
     */
    public MarkInfoType.Ranges createMarkInfoTypeRanges() {
        return new MarkInfoType.Ranges();
    }

    /**
     * Create an instance of {@link OrgInfoEx }
     * 
     */
    public OrgInfoEx createOrgInfoEx() {
        return new OrgInfoEx();
    }

    /**
     * Create an instance of {@link SenderInfo }
     * 
     */
    public SenderInfo createSenderInfo() {
        return new SenderInfo();
    }

    /**
     * Create an instance of {@link Documents.Document }
     * 
     */
    public Documents.Document createDocumentsDocument() {
        return new Documents.Document();
    }

    /**
     * Create an instance of {@link OrgLicenseType }
     * 
     */
    public OrgLicenseType createOrgLicenseType() {
        return new OrgLicenseType();
    }

    /**
     * Create an instance of {@link OrgInfo }
     * 
     */
    public OrgInfo createOrgInfo() {
        return new OrgInfo();
    }

    /**
     * Create an instance of {@link ProductContractType }
     * 
     */
    public ProductContractType createProductContractType() {
        return new ProductContractType();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     * 
     */
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link OrgItemType }
     * 
     */
    public OrgItemType createOrgItemType() {
        return new OrgItemType();
    }

    /**
     * Create an instance of {@link OrgAddressType }
     * 
     */
    public OrgAddressType createOrgAddressType() {
        return new OrgAddressType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link InformBTypeItem }
     * 
     */
    public InformBTypeItem createInformBTypeItem() {
        return new InformBTypeItem();
    }

    /**
     * Create an instance of {@link InformAType }
     * 
     */
    public InformAType createInformAType() {
        return new InformAType();
    }

    /**
     * Create an instance of {@link InformBType }
     * 
     */
    public InformBType createInformBType() {
        return new InformBType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link TicketResultType }
     * 
     */
    public TicketResultType createTicketResultType() {
        return new TicketResultType();
    }

    /**
     * Create an instance of {@link OperationResultType }
     * 
     */
    public OperationResultType createOperationResultType() {
        return new OperationResultType();
    }

    /**
     * Create an instance of {@link TicketType }
     * 
     */
    public TicketType createTicketType() {
        return new TicketType();
    }

    /**
     * Create an instance of {@link TTNActPositionType }
     * 
     */
    public TTNActPositionType createTTNActPositionType() {
        return new TTNActPositionType();
    }

    /**
     * Create an instance of {@link InformBTypeRegItem }
     * 
     */
    public InformBTypeRegItem createInformBTypeRegItem() {
        return new InformBTypeRegItem();
    }

    /**
     * Create an instance of {@link InformARegType }
     * 
     */
    public InformARegType createInformARegType() {
        return new InformARegType();
    }

    /**
     * Create an instance of {@link MarkCodeInfoType }
     * 
     */
    public MarkCodeInfoType createMarkCodeInfoType() {
        return new MarkCodeInfoType();
    }

    /**
     * Create an instance of {@link InformABRegType }
     * 
     */
    public InformABRegType createInformABRegType() {
        return new InformABRegType();
    }

    /**
     * Create an instance of {@link InformABKeyType }
     * 
     */
    public InformABKeyType createInformABKeyType() {
        return new InformABKeyType();
    }

    /**
     * Create an instance of {@link InformInvBRegItem }
     * 
     */
    public InformInvBRegItem createInformInvBRegItem() {
        return new InformInvBRegItem();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link QueryFormAB }
     * 
     */
    public QueryFormAB createQueryFormAB() {
        return new QueryFormAB();
    }

    /**
     * Create an instance of {@link StockPositionType }
     * 
     */
    public StockPositionType createStockPositionType() {
        return new StockPositionType();
    }

    /**
     * Create an instance of {@link ReplyFormA }
     * 
     */
    public ReplyFormA createReplyFormA() {
        return new ReplyFormA();
    }

    /**
     * Create an instance of {@link ReplyFormB }
     * 
     */
    public ReplyFormB createReplyFormB() {
        return new ReplyFormB();
    }

    /**
     * Create an instance of {@link InformBPositionType }
     * 
     */
    public InformBPositionType createInformBPositionType() {
        return new InformBPositionType();
    }

    /**
     * Create an instance of {@link ActWriteOffPositionType }
     * 
     */
    public ActWriteOffPositionType createActWriteOffPositionType() {
        return new ActWriteOffPositionType();
    }

    /**
     * Create an instance of {@link ActWriteOffType.Header }
     * 
     */
    public ActWriteOffType.Header createActWriteOffTypeHeader() {
        return new ActWriteOffType.Header();
    }

    /**
     * Create an instance of {@link ActWriteOffType.Content }
     * 
     */
    public ActWriteOffType.Content createActWriteOffTypeContent() {
        return new ActWriteOffType.Content();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType.Header }
     * 
     */
    public WayBillInformBRegType.Header createWayBillInformBRegTypeHeader() {
        return new WayBillInformBRegType.Header();
    }

    /**
     * Create an instance of {@link WayBillInformBRegType.Content }
     * 
     */
    public WayBillInformBRegType.Content createWayBillInformBRegTypeContent() {
        return new WayBillInformBRegType.Content();
    }

    /**
     * Create an instance of {@link ReplyRests.Products }
     * 
     */
    public ReplyRests.Products createReplyRestsProducts() {
        return new ReplyRests.Products();
    }

    /**
     * Create an instance of {@link ReplyAP.Products }
     * 
     */
    public ReplyAP.Products createReplyAPProducts() {
        return new ReplyAP.Products();
    }

    /**
     * Create an instance of {@link ReplyClient.Clients }
     * 
     */
    public ReplyClient.Clients createReplyClientClients() {
        return new ReplyClient.Clients();
    }

    /**
     * Create an instance of {@link ReplySpirit.Products }
     * 
     */
    public ReplySpirit.Products createReplySpiritProducts() {
        return new ReplySpirit.Products();
    }

    /**
     * Create an instance of {@link ReplySSP.Products }
     * 
     */
    public ReplySSP.Products createReplySSPProducts() {
        return new ReplySSP.Products();
    }

    /**
     * Create an instance of {@link QueryParameters.Parameters }
     * 
     */
    public QueryParameters.Parameters createQueryParametersParameters() {
        return new QueryParameters.Parameters();
    }

    /**
     * Create an instance of {@link InformInvPositionType.InformB }
     * 
     */
    public InformInvPositionType.InformB createInformInvPositionTypeInformB() {
        return new InformInvPositionType.InformB();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg.Header }
     * 
     */
    public ActInventoryInformBReg.Header createActInventoryInformBRegHeader() {
        return new ActInventoryInformBReg.Header();
    }

    /**
     * Create an instance of {@link ActInventoryInformBReg.Content }
     * 
     */
    public ActInventoryInformBReg.Content createActInventoryInformBRegContent() {
        return new ActInventoryInformBReg.Content();
    }

    /**
     * Create an instance of {@link ActChargeOnType.Header }
     * 
     */
    public ActChargeOnType.Header createActChargeOnTypeHeader() {
        return new ActChargeOnType.Header();
    }

    /**
     * Create an instance of {@link ActChargeOnType.Content }
     * 
     */
    public ActChargeOnType.Content createActChargeOnTypeContent() {
        return new ActChargeOnType.Content();
    }

    /**
     * Create an instance of {@link ActChargeOnPositionType.InformAB }
     * 
     */
    public ActChargeOnPositionType.InformAB createActChargeOnPositionTypeInformAB() {
        return new ActChargeOnPositionType.InformAB();
    }

    /**
     * Create an instance of {@link ActInventoryPositionType.InformB }
     * 
     */
    public ActInventoryPositionType.InformB createActInventoryPositionTypeInformB() {
        return new ActInventoryPositionType.InformB();
    }

    /**
     * Create an instance of {@link ActInventoryType.Header }
     * 
     */
    public ActInventoryType.Header createActInventoryTypeHeader() {
        return new ActInventoryType.Header();
    }

    /**
     * Create an instance of {@link ActInventoryType.Content }
     * 
     */
    public ActInventoryType.Content createActInventoryTypeContent() {
        return new ActInventoryType.Content();
    }

    /**
     * Create an instance of {@link ConfirmTicketType.Header }
     * 
     */
    public ConfirmTicketType.Header createConfirmTicketTypeHeader() {
        return new ConfirmTicketType.Header();
    }

    /**
     * Create an instance of {@link WayBillActType.Header }
     * 
     */
    public WayBillActType.Header createWayBillActTypeHeader() {
        return new WayBillActType.Header();
    }

    /**
     * Create an instance of {@link WayBillActType.Content }
     * 
     */
    public WayBillActType.Content createWayBillActTypeContent() {
        return new WayBillActType.Content();
    }

    /**
     * Create an instance of {@link WayBillType.Header }
     * 
     */
    public WayBillType.Header createWayBillTypeHeader() {
        return new WayBillType.Header();
    }

    /**
     * Create an instance of {@link WayBillType.Content }
     * 
     */
    public WayBillType.Content createWayBillTypeContent() {
        return new WayBillType.Content();
    }

    /**
     * Create an instance of {@link MarkInfoType.Ranges.Range }
     * 
     */
    public MarkInfoType.Ranges.Range createMarkInfoTypeRangesRange() {
        return new MarkInfoType.Ranges.Range();
    }

    /**
     * Create an instance of {@link OrgInfoEx.Addresslist }
     * 
     */
    public OrgInfoEx.Addresslist createOrgInfoExAddresslist() {
        return new OrgInfoEx.Addresslist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExINN(String value) {
        return new JAXBElement<String>(_OrgInfoExINN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExRNN(String value) {
        return new JAXBElement<String>(_OrgInfoExRNN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExUNP(String value) {
        return new JAXBElement<String>(_OrgInfoExUNP_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "State", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExState(String value) {
        return new JAXBElement<String>(_OrgInfoExState_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoINN(String value) {
        return new JAXBElement<String>(_OrgInfoExINN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoRNN(String value) {
        return new JAXBElement<String>(_OrgInfoExRNN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoUNP(String value) {
        return new JAXBElement<String>(_OrgInfoExUNP_QNAME, String.class, OrgInfo.class, value);
    }

}
